//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.17 at 01:15:21 PM CEST 
//


package nl.nltaxonomie._8_0_a_2.domein.bd.tuples.bd_bedr_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie._8_0.basis.sbr.types.nl_types.NonNegativeMonetaryNoDecimalsItemType;
import nl.nltaxonomie._8_0_a_2.basis.bd.types.bd_types.Anstring70VItemType;
import org.xbrl._2003.instance.DateItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-bedrijven}NameSubsidiary" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-bedrijven}SettlementDateSubsidiariesTerminationFromTaxentityByDissolutionAndSettlementTitle" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-bedrijven}SettlementSubsidiaryUnpaidDebts" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameSubsidiary",
    "settlementDateSubsidiariesTerminationFromTaxentityByDissolutionAndSettlementTitle",
    "settlementSubsidiaryUnpaidDebts"
})
public class TaxEntityTerminationDissolutionSettlementSubsidiariesSpecification
    extends Placeholder
{

    @XmlElement(name = "NameSubsidiary", namespace = "http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-bedrijven")
    protected Anstring70VItemType nameSubsidiary;
    @XmlElement(name = "SettlementDateSubsidiariesTerminationFromTaxentityByDissolutionAndSettlementTitle", namespace = "http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-bedrijven")
    protected DateItemType settlementDateSubsidiariesTerminationFromTaxentityByDissolutionAndSettlementTitle;
    @XmlElement(name = "SettlementSubsidiaryUnpaidDebts", namespace = "http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-bedrijven")
    protected NonNegativeMonetaryNoDecimalsItemType settlementSubsidiaryUnpaidDebts;

    /**
     * Gets the value of the nameSubsidiary property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring70VItemType }
     *     
     */
    public Anstring70VItemType getNameSubsidiary() {
        return nameSubsidiary;
    }

    /**
     * Sets the value of the nameSubsidiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring70VItemType }
     *     
     */
    public void setNameSubsidiary(Anstring70VItemType value) {
        this.nameSubsidiary = value;
    }

    /**
     * Gets the value of the settlementDateSubsidiariesTerminationFromTaxentityByDissolutionAndSettlementTitle property.
     * 
     * @return
     *     possible object is
     *     {@link DateItemType }
     *     
     */
    public DateItemType getSettlementDateSubsidiariesTerminationFromTaxentityByDissolutionAndSettlementTitle() {
        return settlementDateSubsidiariesTerminationFromTaxentityByDissolutionAndSettlementTitle;
    }

    /**
     * Sets the value of the settlementDateSubsidiariesTerminationFromTaxentityByDissolutionAndSettlementTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateItemType }
     *     
     */
    public void setSettlementDateSubsidiariesTerminationFromTaxentityByDissolutionAndSettlementTitle(DateItemType value) {
        this.settlementDateSubsidiariesTerminationFromTaxentityByDissolutionAndSettlementTitle = value;
    }

    /**
     * Gets the value of the settlementSubsidiaryUnpaidDebts property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getSettlementSubsidiaryUnpaidDebts() {
        return settlementSubsidiaryUnpaidDebts;
    }

    /**
     * Sets the value of the settlementSubsidiaryUnpaidDebts property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setSettlementSubsidiaryUnpaidDebts(NonNegativeMonetaryNoDecimalsItemType value) {
        this.settlementSubsidiaryUnpaidDebts = value;
    }

}
