//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.16 at 05:37:42 PM CET 
//


package nl.nltaxonomie._7_0.domein.bd.tuples.bd_burg_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie._7_0.basis.bd.types.bd_types.Anstring70VItemType;
import nl.nltaxonomie._7_0.basis.sbr.types.nl_types.MonetaryNoDecimalsItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0/basis/bd/items/bd-burgers}IncomePreviousWorkAbroadWithoutDutchWageTaxAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0/basis/bd/items/bd-burgers}NameAndAddressForeignBenefitsAgency" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "incomePreviousWorkAbroadWithoutDutchWageTaxAmount",
    "nameAndAddressForeignBenefitsAgency"
})
public class IncomePreviousWorkAbroadWithoutDutchWageTaxSpecification
    extends Placeholder
{

    @XmlElement(name = "IncomePreviousWorkAbroadWithoutDutchWageTaxAmount", namespace = "http://www.nltaxonomie.nl/7.0/basis/bd/items/bd-burgers")
    protected MonetaryNoDecimalsItemType incomePreviousWorkAbroadWithoutDutchWageTaxAmount;
    @XmlElement(name = "NameAndAddressForeignBenefitsAgency", namespace = "http://www.nltaxonomie.nl/7.0/basis/bd/items/bd-burgers")
    protected Anstring70VItemType nameAndAddressForeignBenefitsAgency;

    /**
     * Gets the value of the incomePreviousWorkAbroadWithoutDutchWageTaxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getIncomePreviousWorkAbroadWithoutDutchWageTaxAmount() {
        return incomePreviousWorkAbroadWithoutDutchWageTaxAmount;
    }

    /**
     * Sets the value of the incomePreviousWorkAbroadWithoutDutchWageTaxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setIncomePreviousWorkAbroadWithoutDutchWageTaxAmount(MonetaryNoDecimalsItemType value) {
        this.incomePreviousWorkAbroadWithoutDutchWageTaxAmount = value;
    }

    /**
     * Gets the value of the nameAndAddressForeignBenefitsAgency property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring70VItemType }
     *     
     */
    public Anstring70VItemType getNameAndAddressForeignBenefitsAgency() {
        return nameAndAddressForeignBenefitsAgency;
    }

    /**
     * Sets the value of the nameAndAddressForeignBenefitsAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring70VItemType }
     *     
     */
    public void setNameAndAddressForeignBenefitsAgency(Anstring70VItemType value) {
        this.nameAndAddressForeignBenefitsAgency = value;
    }

}
