//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 09:06:01 PM CET 
//


package nl.nltaxonomie._7_0_b_1.domein.bd.tuples.bd_burg_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie._7_0.basis.sbr.types.nl_types.NonNegativeMonetaryNoDecimalsItemType;
import nl.nltaxonomie._7_0_b_1.basis.bd.types.bd_types.Anstring20VItemType;
import nl.nltaxonomie._7_0_b_1.basis.bd.types.bd_types.Anstring60VItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers}PremiumsAnnuitiesInsurerName" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers}PremiumsAnnuitiesPaidAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers}PremiumsAnnuitiesPolicyNumber" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "premiumsAnnuitiesInsurerName",
    "premiumsAnnuitiesPaidAmount",
    "premiumsAnnuitiesPolicyNumber"
})
public class PremiumsAnnuitiesSpecification
    extends Placeholder
{

    @XmlElement(name = "PremiumsAnnuitiesInsurerName", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers")
    protected Anstring60VItemType premiumsAnnuitiesInsurerName;
    @XmlElement(name = "PremiumsAnnuitiesPaidAmount", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers")
    protected NonNegativeMonetaryNoDecimalsItemType premiumsAnnuitiesPaidAmount;
    @XmlElement(name = "PremiumsAnnuitiesPolicyNumber", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers")
    protected Anstring20VItemType premiumsAnnuitiesPolicyNumber;

    /**
     * Gets the value of the premiumsAnnuitiesInsurerName property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring60VItemType }
     *     
     */
    public Anstring60VItemType getPremiumsAnnuitiesInsurerName() {
        return premiumsAnnuitiesInsurerName;
    }

    /**
     * Sets the value of the premiumsAnnuitiesInsurerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring60VItemType }
     *     
     */
    public void setPremiumsAnnuitiesInsurerName(Anstring60VItemType value) {
        this.premiumsAnnuitiesInsurerName = value;
    }

    /**
     * Gets the value of the premiumsAnnuitiesPaidAmount property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getPremiumsAnnuitiesPaidAmount() {
        return premiumsAnnuitiesPaidAmount;
    }

    /**
     * Sets the value of the premiumsAnnuitiesPaidAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setPremiumsAnnuitiesPaidAmount(NonNegativeMonetaryNoDecimalsItemType value) {
        this.premiumsAnnuitiesPaidAmount = value;
    }

    /**
     * Gets the value of the premiumsAnnuitiesPolicyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring20VItemType }
     *     
     */
    public Anstring20VItemType getPremiumsAnnuitiesPolicyNumber() {
        return premiumsAnnuitiesPolicyNumber;
    }

    /**
     * Sets the value of the premiumsAnnuitiesPolicyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring20VItemType }
     *     
     */
    public void setPremiumsAnnuitiesPolicyNumber(Anstring20VItemType value) {
        this.premiumsAnnuitiesPolicyNumber = value;
    }

}
