//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 09:06:01 PM CET 
//


package nl.nltaxonomie._7_0_b_1.domein.bd.tuples.bd_burg_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie._7_0.basis.sbr.types.nl_types.NonNegativeMonetaryNoDecimalsItemType;
import nl.nltaxonomie._7_0_b_1.basis.bd.types.bd_types.Anstring35VItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers}AnnuityRedemptionAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers}PayingAgencyName" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers}WageTaxWithheldAmount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "annuityRedemptionAmount",
    "payingAgencyName",
    "wageTaxWithheldAmount"
})
public class RedemptionAnnuitiesCoveredByWagetaxSpecification
    extends Placeholder
{

    @XmlElement(name = "AnnuityRedemptionAmount", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers")
    protected NonNegativeMonetaryNoDecimalsItemType annuityRedemptionAmount;
    @XmlElement(name = "PayingAgencyName", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers")
    protected Anstring35VItemType payingAgencyName;
    @XmlElement(name = "WageTaxWithheldAmount", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers")
    protected NonNegativeMonetaryNoDecimalsItemType wageTaxWithheldAmount;

    /**
     * Gets the value of the annuityRedemptionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getAnnuityRedemptionAmount() {
        return annuityRedemptionAmount;
    }

    /**
     * Sets the value of the annuityRedemptionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setAnnuityRedemptionAmount(NonNegativeMonetaryNoDecimalsItemType value) {
        this.annuityRedemptionAmount = value;
    }

    /**
     * Gets the value of the payingAgencyName property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring35VItemType }
     *     
     */
    public Anstring35VItemType getPayingAgencyName() {
        return payingAgencyName;
    }

    /**
     * Sets the value of the payingAgencyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring35VItemType }
     *     
     */
    public void setPayingAgencyName(Anstring35VItemType value) {
        this.payingAgencyName = value;
    }

    /**
     * Gets the value of the wageTaxWithheldAmount property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getWageTaxWithheldAmount() {
        return wageTaxWithheldAmount;
    }

    /**
     * Sets the value of the wageTaxWithheldAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setWageTaxWithheldAmount(NonNegativeMonetaryNoDecimalsItemType value) {
        this.wageTaxWithheldAmount = value;
    }

}
