//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 09:06:01 PM CET 
//


package nl.nltaxonomie._7_0_b_1.domein.bd.tuples.bd_burg_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie.iso.iso3166.IsoCountryCodes3CharactersItemType;
import org.xbrl._2003.instance.DateItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0/basis/sbr/items/nl-common-data}CountryCodeISO" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers}CountryResidenceEndDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers}CountryResidenceStartDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "countryCodeISO",
    "countryResidenceEndDate",
    "countryResidenceStartDate"
})
public class ResidenceForeignCountryTitle
    extends Placeholder
{

    @XmlElement(name = "CountryCodeISO", namespace = "http://www.nltaxonomie.nl/7.0/basis/sbr/items/nl-common-data")
    protected IsoCountryCodes3CharactersItemType countryCodeISO;
    @XmlElement(name = "CountryResidenceEndDate", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers")
    protected DateItemType countryResidenceEndDate;
    @XmlElement(name = "CountryResidenceStartDate", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-burgers")
    protected DateItemType countryResidenceStartDate;

    /**
     * Gets the value of the countryCodeISO property.
     * 
     * @return
     *     possible object is
     *     {@link IsoCountryCodes3CharactersItemType }
     *     
     */
    public IsoCountryCodes3CharactersItemType getCountryCodeISO() {
        return countryCodeISO;
    }

    /**
     * Sets the value of the countryCodeISO property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsoCountryCodes3CharactersItemType }
     *     
     */
    public void setCountryCodeISO(IsoCountryCodes3CharactersItemType value) {
        this.countryCodeISO = value;
    }

    /**
     * Gets the value of the countryResidenceEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateItemType }
     *     
     */
    public DateItemType getCountryResidenceEndDate() {
        return countryResidenceEndDate;
    }

    /**
     * Sets the value of the countryResidenceEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateItemType }
     *     
     */
    public void setCountryResidenceEndDate(DateItemType value) {
        this.countryResidenceEndDate = value;
    }

    /**
     * Gets the value of the countryResidenceStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateItemType }
     *     
     */
    public DateItemType getCountryResidenceStartDate() {
        return countryResidenceStartDate;
    }

    /**
     * Sets the value of the countryResidenceStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateItemType }
     *     
     */
    public void setCountryResidenceStartDate(DateItemType value) {
        this.countryResidenceStartDate = value;
    }

}
