//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 09:06:01 PM CET 
//


package nl.nltaxonomie._7_0_b_1.domein.kvk.tuples.kvk_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import org.xbrl._2003.instance.StringItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data}ExceptionalItemsDescription" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data}ExceptionalItemsFinancialImpact" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data}ExceptionalItemsLineItemsWhereIncluded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "exceptionalItemsDescription",
    "exceptionalItemsFinancialImpact",
    "exceptionalItemsLineItemsWhereIncluded"
})
public class ExceptionalItemsSpecification
    extends Placeholder
{

    @XmlElement(name = "ExceptionalItemsDescription", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data")
    protected StringItemType exceptionalItemsDescription;
    @XmlElement(name = "ExceptionalItemsFinancialImpact", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data")
    protected StringItemType exceptionalItemsFinancialImpact;
    @XmlElement(name = "ExceptionalItemsLineItemsWhereIncluded", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data")
    protected StringItemType exceptionalItemsLineItemsWhereIncluded;

    /**
     * Gets the value of the exceptionalItemsDescription property.
     * 
     * @return
     *     possible object is
     *     {@link StringItemType }
     *     
     */
    public StringItemType getExceptionalItemsDescription() {
        return exceptionalItemsDescription;
    }

    /**
     * Sets the value of the exceptionalItemsDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringItemType }
     *     
     */
    public void setExceptionalItemsDescription(StringItemType value) {
        this.exceptionalItemsDescription = value;
    }

    /**
     * Gets the value of the exceptionalItemsFinancialImpact property.
     * 
     * @return
     *     possible object is
     *     {@link StringItemType }
     *     
     */
    public StringItemType getExceptionalItemsFinancialImpact() {
        return exceptionalItemsFinancialImpact;
    }

    /**
     * Sets the value of the exceptionalItemsFinancialImpact property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringItemType }
     *     
     */
    public void setExceptionalItemsFinancialImpact(StringItemType value) {
        this.exceptionalItemsFinancialImpact = value;
    }

    /**
     * Gets the value of the exceptionalItemsLineItemsWhereIncluded property.
     * 
     * @return
     *     possible object is
     *     {@link StringItemType }
     *     
     */
    public StringItemType getExceptionalItemsLineItemsWhereIncluded() {
        return exceptionalItemsLineItemsWhereIncluded;
    }

    /**
     * Sets the value of the exceptionalItemsLineItemsWhereIncluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringItemType }
     *     
     */
    public void setExceptionalItemsLineItemsWhereIncluded(StringItemType value) {
        this.exceptionalItemsLineItemsWhereIncluded = value;
    }

}
