//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 09:06:01 PM CET 
//


package nl.nltaxonomie._7_0_b_1.domein.kvk.tuples.kvk_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie._7_0.basis.sbr.types.nl_types.MonetaryNoDecimalsItemType;
import nl.nltaxonomie._7_0_b_1.basis.kvk.types.kvk_codes.DirectorItemType;
import nl.nltaxonomie._7_0_b_1.basis.kvk.types.kvk_codes.LoanAdvanceGuaranteeItemType;
import org.xbrl._2003.instance.StringItemType;
import org.xbrl.dtr.type.numeric.PercentItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data}LoansAdvancesGuaranteesOnBehalfOfDirectorsTypeLoanAdvanceGuarantee" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data}LoansAdvancesGuaranteesOnBehalfOfDirectorsTypeDirector" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data}LoansAdvancesGuaranteesOnBehalfOfDirectorsOutstandingAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data}LoansAdvancesGuaranteesOnBehalfOfDirectorsInterestRate" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data}LoansAdvancesGuaranteesOnBehalfOfDirectorsConditions" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data}LoansAdvancesGuaranteesOnBehalfOfDirectorsRepayments" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "loansAdvancesGuaranteesOnBehalfOfDirectorsTypeLoanAdvanceGuarantee",
    "loansAdvancesGuaranteesOnBehalfOfDirectorsTypeDirector",
    "loansAdvancesGuaranteesOnBehalfOfDirectorsOutstandingAmount",
    "loansAdvancesGuaranteesOnBehalfOfDirectorsInterestRate",
    "loansAdvancesGuaranteesOnBehalfOfDirectorsConditions",
    "loansAdvancesGuaranteesOnBehalfOfDirectorsRepayments"
})
public class LoansAdvancesGuaranteesOnBehalfOfDirectorsSpecification
    extends Placeholder
{

    @XmlElement(name = "LoansAdvancesGuaranteesOnBehalfOfDirectorsTypeLoanAdvanceGuarantee", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data")
    protected LoanAdvanceGuaranteeItemType loansAdvancesGuaranteesOnBehalfOfDirectorsTypeLoanAdvanceGuarantee;
    @XmlElement(name = "LoansAdvancesGuaranteesOnBehalfOfDirectorsTypeDirector", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data")
    protected DirectorItemType loansAdvancesGuaranteesOnBehalfOfDirectorsTypeDirector;
    @XmlElement(name = "LoansAdvancesGuaranteesOnBehalfOfDirectorsOutstandingAmount", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data")
    protected MonetaryNoDecimalsItemType loansAdvancesGuaranteesOnBehalfOfDirectorsOutstandingAmount;
    @XmlElement(name = "LoansAdvancesGuaranteesOnBehalfOfDirectorsInterestRate", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data")
    protected PercentItemType loansAdvancesGuaranteesOnBehalfOfDirectorsInterestRate;
    @XmlElement(name = "LoansAdvancesGuaranteesOnBehalfOfDirectorsConditions", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data")
    protected StringItemType loansAdvancesGuaranteesOnBehalfOfDirectorsConditions;
    @XmlElement(name = "LoansAdvancesGuaranteesOnBehalfOfDirectorsRepayments", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/kvk/items/kvk-data")
    protected MonetaryNoDecimalsItemType loansAdvancesGuaranteesOnBehalfOfDirectorsRepayments;

    /**
     * Gets the value of the loansAdvancesGuaranteesOnBehalfOfDirectorsTypeLoanAdvanceGuarantee property.
     * 
     * @return
     *     possible object is
     *     {@link LoanAdvanceGuaranteeItemType }
     *     
     */
    public LoanAdvanceGuaranteeItemType getLoansAdvancesGuaranteesOnBehalfOfDirectorsTypeLoanAdvanceGuarantee() {
        return loansAdvancesGuaranteesOnBehalfOfDirectorsTypeLoanAdvanceGuarantee;
    }

    /**
     * Sets the value of the loansAdvancesGuaranteesOnBehalfOfDirectorsTypeLoanAdvanceGuarantee property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanAdvanceGuaranteeItemType }
     *     
     */
    public void setLoansAdvancesGuaranteesOnBehalfOfDirectorsTypeLoanAdvanceGuarantee(LoanAdvanceGuaranteeItemType value) {
        this.loansAdvancesGuaranteesOnBehalfOfDirectorsTypeLoanAdvanceGuarantee = value;
    }

    /**
     * Gets the value of the loansAdvancesGuaranteesOnBehalfOfDirectorsTypeDirector property.
     * 
     * @return
     *     possible object is
     *     {@link DirectorItemType }
     *     
     */
    public DirectorItemType getLoansAdvancesGuaranteesOnBehalfOfDirectorsTypeDirector() {
        return loansAdvancesGuaranteesOnBehalfOfDirectorsTypeDirector;
    }

    /**
     * Sets the value of the loansAdvancesGuaranteesOnBehalfOfDirectorsTypeDirector property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectorItemType }
     *     
     */
    public void setLoansAdvancesGuaranteesOnBehalfOfDirectorsTypeDirector(DirectorItemType value) {
        this.loansAdvancesGuaranteesOnBehalfOfDirectorsTypeDirector = value;
    }

    /**
     * Gets the value of the loansAdvancesGuaranteesOnBehalfOfDirectorsOutstandingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getLoansAdvancesGuaranteesOnBehalfOfDirectorsOutstandingAmount() {
        return loansAdvancesGuaranteesOnBehalfOfDirectorsOutstandingAmount;
    }

    /**
     * Sets the value of the loansAdvancesGuaranteesOnBehalfOfDirectorsOutstandingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setLoansAdvancesGuaranteesOnBehalfOfDirectorsOutstandingAmount(MonetaryNoDecimalsItemType value) {
        this.loansAdvancesGuaranteesOnBehalfOfDirectorsOutstandingAmount = value;
    }

    /**
     * Gets the value of the loansAdvancesGuaranteesOnBehalfOfDirectorsInterestRate property.
     * 
     * @return
     *     possible object is
     *     {@link PercentItemType }
     *     
     */
    public PercentItemType getLoansAdvancesGuaranteesOnBehalfOfDirectorsInterestRate() {
        return loansAdvancesGuaranteesOnBehalfOfDirectorsInterestRate;
    }

    /**
     * Sets the value of the loansAdvancesGuaranteesOnBehalfOfDirectorsInterestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PercentItemType }
     *     
     */
    public void setLoansAdvancesGuaranteesOnBehalfOfDirectorsInterestRate(PercentItemType value) {
        this.loansAdvancesGuaranteesOnBehalfOfDirectorsInterestRate = value;
    }

    /**
     * Gets the value of the loansAdvancesGuaranteesOnBehalfOfDirectorsConditions property.
     * 
     * @return
     *     possible object is
     *     {@link StringItemType }
     *     
     */
    public StringItemType getLoansAdvancesGuaranteesOnBehalfOfDirectorsConditions() {
        return loansAdvancesGuaranteesOnBehalfOfDirectorsConditions;
    }

    /**
     * Sets the value of the loansAdvancesGuaranteesOnBehalfOfDirectorsConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringItemType }
     *     
     */
    public void setLoansAdvancesGuaranteesOnBehalfOfDirectorsConditions(StringItemType value) {
        this.loansAdvancesGuaranteesOnBehalfOfDirectorsConditions = value;
    }

    /**
     * Gets the value of the loansAdvancesGuaranteesOnBehalfOfDirectorsRepayments property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getLoansAdvancesGuaranteesOnBehalfOfDirectorsRepayments() {
        return loansAdvancesGuaranteesOnBehalfOfDirectorsRepayments;
    }

    /**
     * Sets the value of the loansAdvancesGuaranteesOnBehalfOfDirectorsRepayments property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setLoansAdvancesGuaranteesOnBehalfOfDirectorsRepayments(MonetaryNoDecimalsItemType value) {
        this.loansAdvancesGuaranteesOnBehalfOfDirectorsRepayments = value;
    }

}
