//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.09 at 10:28:44 PM CET 
//


package nl.nltaxonomie._8_0.domein.bd.tuples.bd_burg_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie._8_0.basis.bd.types.bd_types.Anstring34VItemType;
import nl.nltaxonomie._8_0.basis.bd.types.bd_types.Anstring60VItemType;
import nl.nltaxonomie._8_0.basis.sbr.types.nl_types.MonetaryNoDecimalsItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-burgers}OwnHouseDebtAccountNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-burgers}OwnHouseDebtCostMoneyLoansDeductible" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-burgers}OwnHouseDebtDescription" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-burgers}OwnHouseDebtInterestDeductible" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-burgers}OwnHouseDebtReportedPeriod" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ownHouseDebtAccountNumber",
    "ownHouseDebtCostMoneyLoansDeductible",
    "ownHouseDebtDescription",
    "ownHouseDebtInterestDeductible",
    "ownHouseDebtReportedPeriod"
})
public class OwnHouseDebtSpecification
    extends Placeholder
{

    @XmlElement(name = "OwnHouseDebtAccountNumber", namespace = "http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-burgers")
    protected Anstring34VItemType ownHouseDebtAccountNumber;
    @XmlElement(name = "OwnHouseDebtCostMoneyLoansDeductible", namespace = "http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-burgers")
    protected MonetaryNoDecimalsItemType ownHouseDebtCostMoneyLoansDeductible;
    @XmlElement(name = "OwnHouseDebtDescription", namespace = "http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-burgers")
    protected Anstring60VItemType ownHouseDebtDescription;
    @XmlElement(name = "OwnHouseDebtInterestDeductible", namespace = "http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-burgers")
    protected MonetaryNoDecimalsItemType ownHouseDebtInterestDeductible;
    @XmlElement(name = "OwnHouseDebtReportedPeriod", namespace = "http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-burgers")
    protected MonetaryNoDecimalsItemType ownHouseDebtReportedPeriod;

    /**
     * Gets the value of the ownHouseDebtAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring34VItemType }
     *     
     */
    public Anstring34VItemType getOwnHouseDebtAccountNumber() {
        return ownHouseDebtAccountNumber;
    }

    /**
     * Sets the value of the ownHouseDebtAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring34VItemType }
     *     
     */
    public void setOwnHouseDebtAccountNumber(Anstring34VItemType value) {
        this.ownHouseDebtAccountNumber = value;
    }

    /**
     * Gets the value of the ownHouseDebtCostMoneyLoansDeductible property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getOwnHouseDebtCostMoneyLoansDeductible() {
        return ownHouseDebtCostMoneyLoansDeductible;
    }

    /**
     * Sets the value of the ownHouseDebtCostMoneyLoansDeductible property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setOwnHouseDebtCostMoneyLoansDeductible(MonetaryNoDecimalsItemType value) {
        this.ownHouseDebtCostMoneyLoansDeductible = value;
    }

    /**
     * Gets the value of the ownHouseDebtDescription property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring60VItemType }
     *     
     */
    public Anstring60VItemType getOwnHouseDebtDescription() {
        return ownHouseDebtDescription;
    }

    /**
     * Sets the value of the ownHouseDebtDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring60VItemType }
     *     
     */
    public void setOwnHouseDebtDescription(Anstring60VItemType value) {
        this.ownHouseDebtDescription = value;
    }

    /**
     * Gets the value of the ownHouseDebtInterestDeductible property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getOwnHouseDebtInterestDeductible() {
        return ownHouseDebtInterestDeductible;
    }

    /**
     * Sets the value of the ownHouseDebtInterestDeductible property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setOwnHouseDebtInterestDeductible(MonetaryNoDecimalsItemType value) {
        this.ownHouseDebtInterestDeductible = value;
    }

    /**
     * Gets the value of the ownHouseDebtReportedPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getOwnHouseDebtReportedPeriod() {
        return ownHouseDebtReportedPeriod;
    }

    /**
     * Sets the value of the ownHouseDebtReportedPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setOwnHouseDebtReportedPeriod(MonetaryNoDecimalsItemType value) {
        this.ownHouseDebtReportedPeriod = value;
    }

}
