//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.09 at 08:39:58 PM CEST 
//


package nl.nltaxonomie.nt12.bd._20171213.dictionary.bd_tuples;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie.nt12.bd._20171213.dictionary.bd_types.Anstring70VItemType;
import nl.nltaxonomie.nt12.sbr._20170515.dictionary.nl_types.MonetaryNoDecimalsItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt12/bd/20171213/dictionary/bd-data}ImmovablePropertyInConncetionWithResultFromActivitiesDescription" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt12/bd/20171213/dictionary/bd-data}ImmovablePropertyInConnectionWithResultFromActivitiesValue" maxOccurs="2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "immovablePropertyInConncetionWithResultFromActivitiesDescription",
    "immovablePropertyInConnectionWithResultFromActivitiesValue"
})
public class ImmovablePropertyInConnectionWithResultFromActivitiesSpecification
    extends Placeholder
{

    @XmlElement(name = "ImmovablePropertyInConncetionWithResultFromActivitiesDescription", namespace = "http://www.nltaxonomie.nl/nt12/bd/20171213/dictionary/bd-data")
    protected Anstring70VItemType immovablePropertyInConncetionWithResultFromActivitiesDescription;
    @XmlElement(name = "ImmovablePropertyInConnectionWithResultFromActivitiesValue", namespace = "http://www.nltaxonomie.nl/nt12/bd/20171213/dictionary/bd-data")
    protected List<MonetaryNoDecimalsItemType> immovablePropertyInConnectionWithResultFromActivitiesValue;

    /**
     * Gets the value of the immovablePropertyInConncetionWithResultFromActivitiesDescription property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring70VItemType }
     *     
     */
    public Anstring70VItemType getImmovablePropertyInConncetionWithResultFromActivitiesDescription() {
        return immovablePropertyInConncetionWithResultFromActivitiesDescription;
    }

    /**
     * Sets the value of the immovablePropertyInConncetionWithResultFromActivitiesDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring70VItemType }
     *     
     */
    public void setImmovablePropertyInConncetionWithResultFromActivitiesDescription(Anstring70VItemType value) {
        this.immovablePropertyInConncetionWithResultFromActivitiesDescription = value;
    }

    /**
     * Gets the value of the immovablePropertyInConnectionWithResultFromActivitiesValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the immovablePropertyInConnectionWithResultFromActivitiesValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImmovablePropertyInConnectionWithResultFromActivitiesValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonetaryNoDecimalsItemType }
     * 
     * 
     */
    public List<MonetaryNoDecimalsItemType> getImmovablePropertyInConnectionWithResultFromActivitiesValue() {
        if (immovablePropertyInConnectionWithResultFromActivitiesValue == null) {
            immovablePropertyInConnectionWithResultFromActivitiesValue = new ArrayList<MonetaryNoDecimalsItemType>();
        }
        return this.immovablePropertyInConnectionWithResultFromActivitiesValue;
    }

}
