//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.16 at 09:30:36 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-codes")
package nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_codes;
