//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.09 at 10:28:44 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(xmlns = { @XmlNs(prefix = "iso4217", namespaceURI = "http://www.xbrl.org/2003/iso4217") }, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.nltaxonomie.iso.iso4217;

import javax.xml.bind.annotation.XmlNs;
