//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.16 at 05:37:42 PM CET 
//


package nl.nltaxonomie._7_0.domein.bd.tuples.bd_alg_tuples;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.nltaxonomie._7_0.domein.bd.tuples.bd_alg_tuples package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConsultantAdvisorCorrespondentTitle_QNAME = new QName("http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", "ConsultantAdvisorCorrespondentTitle");
    private final static QName _CorrespondentServicebureau_QNAME = new QName("http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", "CorrespondentServicebureau");
    private final static QName _CorrespondentDeclarant_QNAME = new QName("http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", "CorrespondentDeclarant");
    private final static QName _CorrespondentConsultantAdvisor_QNAME = new QName("http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", "CorrespondentConsultantAdvisor");
    private final static QName _AddressDutchTitle_QNAME = new QName("http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", "AddressDutchTitle");
    private final static QName _TaxConsultantSpecification_QNAME = new QName("http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", "TaxConsultantSpecification");
    private final static QName _AddressAbroadTitle_QNAME = new QName("http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", "AddressAbroadTitle");
    private final static QName _ConsultantAdvisorTitle_QNAME = new QName("http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", "ConsultantAdvisorTitle");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.nltaxonomie._7_0.domein.bd.tuples.bd_alg_tuples
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultantAdvisorTitle }
     * 
     */
    public ConsultantAdvisorTitle createConsultantAdvisorTitle() {
        return new ConsultantAdvisorTitle();
    }

    /**
     * Create an instance of {@link AddressDutchTitle }
     * 
     */
    public AddressDutchTitle createAddressDutchTitle() {
        return new AddressDutchTitle();
    }

    /**
     * Create an instance of {@link ConsultantAdvisorCorrespondentTitle }
     * 
     */
    public ConsultantAdvisorCorrespondentTitle createConsultantAdvisorCorrespondentTitle() {
        return new ConsultantAdvisorCorrespondentTitle();
    }

    /**
     * Create an instance of {@link CorrespondentDeclarant }
     * 
     */
    public CorrespondentDeclarant createCorrespondentDeclarant() {
        return new CorrespondentDeclarant();
    }

    /**
     * Create an instance of {@link CorrespondentServicebureau }
     * 
     */
    public CorrespondentServicebureau createCorrespondentServicebureau() {
        return new CorrespondentServicebureau();
    }

    /**
     * Create an instance of {@link TaxConsultantSpecification }
     * 
     */
    public TaxConsultantSpecification createTaxConsultantSpecification() {
        return new TaxConsultantSpecification();
    }

    /**
     * Create an instance of {@link CorrespondentConsultantAdvisor }
     * 
     */
    public CorrespondentConsultantAdvisor createCorrespondentConsultantAdvisor() {
        return new CorrespondentConsultantAdvisor();
    }

    /**
     * Create an instance of {@link AddressAbroadTitle }
     * 
     */
    public AddressAbroadTitle createAddressAbroadTitle() {
        return new AddressAbroadTitle();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultantAdvisorCorrespondentTitle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", name = "ConsultantAdvisorCorrespondentTitle", substitutionHeadNamespace = "http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension", substitutionHeadName = "presentationTuple")
    public JAXBElement<ConsultantAdvisorCorrespondentTitle> createConsultantAdvisorCorrespondentTitle(ConsultantAdvisorCorrespondentTitle value) {
        return new JAXBElement<ConsultantAdvisorCorrespondentTitle>(_ConsultantAdvisorCorrespondentTitle_QNAME, ConsultantAdvisorCorrespondentTitle.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorrespondentServicebureau }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", name = "CorrespondentServicebureau", substitutionHeadNamespace = "http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension", substitutionHeadName = "presentationTuple")
    public JAXBElement<CorrespondentServicebureau> createCorrespondentServicebureau(CorrespondentServicebureau value) {
        return new JAXBElement<CorrespondentServicebureau>(_CorrespondentServicebureau_QNAME, CorrespondentServicebureau.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorrespondentDeclarant }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", name = "CorrespondentDeclarant", substitutionHeadNamespace = "http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension", substitutionHeadName = "presentationTuple")
    public JAXBElement<CorrespondentDeclarant> createCorrespondentDeclarant(CorrespondentDeclarant value) {
        return new JAXBElement<CorrespondentDeclarant>(_CorrespondentDeclarant_QNAME, CorrespondentDeclarant.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorrespondentConsultantAdvisor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", name = "CorrespondentConsultantAdvisor", substitutionHeadNamespace = "http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension", substitutionHeadName = "presentationTuple")
    public JAXBElement<CorrespondentConsultantAdvisor> createCorrespondentConsultantAdvisor(CorrespondentConsultantAdvisor value) {
        return new JAXBElement<CorrespondentConsultantAdvisor>(_CorrespondentConsultantAdvisor_QNAME, CorrespondentConsultantAdvisor.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressDutchTitle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", name = "AddressDutchTitle", substitutionHeadNamespace = "http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension", substitutionHeadName = "presentationTuple")
    public JAXBElement<AddressDutchTitle> createAddressDutchTitle(AddressDutchTitle value) {
        return new JAXBElement<AddressDutchTitle>(_AddressDutchTitle_QNAME, AddressDutchTitle.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaxConsultantSpecification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", name = "TaxConsultantSpecification", substitutionHeadNamespace = "http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension", substitutionHeadName = "presentationTuple")
    public JAXBElement<TaxConsultantSpecification> createTaxConsultantSpecification(TaxConsultantSpecification value) {
        return new JAXBElement<TaxConsultantSpecification>(_TaxConsultantSpecification_QNAME, TaxConsultantSpecification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressAbroadTitle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", name = "AddressAbroadTitle", substitutionHeadNamespace = "http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension", substitutionHeadName = "presentationTuple")
    public JAXBElement<AddressAbroadTitle> createAddressAbroadTitle(AddressAbroadTitle value) {
        return new JAXBElement<AddressAbroadTitle>(_AddressAbroadTitle_QNAME, AddressAbroadTitle.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultantAdvisorTitle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/7.0/domein/bd/tuples/bd-alg-tuples", name = "ConsultantAdvisorTitle", substitutionHeadNamespace = "http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension", substitutionHeadName = "presentationTuple")
    public JAXBElement<ConsultantAdvisorTitle> createConsultantAdvisorTitle(ConsultantAdvisorTitle value) {
        return new JAXBElement<ConsultantAdvisorTitle>(_ConsultantAdvisorTitle_QNAME, ConsultantAdvisorTitle.class, null, value);
    }

}
