//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.10 at 11:10:53 AM CEST 
//


package nl.nltaxonomie.nt13.bd._20181212_b.dictionary.bd_tuples;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie.nt13.bd._20181212_b.dictionary.bd_types.Anstring70VItemType;
import nl.nltaxonomie.nt13.sbr._20180301.dictionary.nl_types.MonetaryNoDecimalsItemType;
import nl.nltaxonomie.nt13.sbr._20180301.dictionary.nl_types.NonNegativeMonetaryNoDecimalsItemType;
import org.xbrl._2003.instance.BooleanItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}AgrarianNatureManagementSubsidyFiscal" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}AgriculturalActivitiesBusinessName" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}AgriculturalAssetsOtherFiscal" maxOccurs="2" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}AgriculturalAssetsOtherPurchaseOrProductionCostsFiscalAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}AgriculturalAssetsOtherResidualValueFiscal" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}AgriculturalEnterpriseType" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}AgriculturalStockOtherFiscal" maxOccurs="2" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}AnimalsFiscal" maxOccurs="2" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}AnimalsPurchaseOrProductionCostsFiscalAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}AnimalsResidualValueFiscal" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}CartageFiscal" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}DemolitionInConnectionWithPurchaseOrDisposalLandToFarmerExists" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}DisposalLandInConnectionWithAgriculturalActivitiesExists" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}DisposalLandToFarmerExists" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}DisposalPropertiesExists" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}DisposalPropertiesFiscalReserveWriteOffExists" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}FieldEquipmentFiscal" maxOccurs="2" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}FlowerBulbsFiscal" maxOccurs="2" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}MushroomsFiscal" maxOccurs="2" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}NationalAgriculturalStandardsDeviationExists" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}PlantsAndSeedsAndStandsFiscal" maxOccurs="2" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}PlantsAndSeedsAndStandsResidualValueFiscal" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}PlantsSeedsAndStandsPurchaseOrProductionCostsFiscalAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}ProductionRightsDepreciationFiscal" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}ProductionRightsFiscal" maxOccurs="2" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}ProductionRightsPurchaseOrProductionCostsFiscal" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}SoilBelgiumOrGemanyExists" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}StockAnimalsFiscal" maxOccurs="2" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}WorkThirdPartiesFiscal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "agrarianNatureManagementSubsidyFiscal",
    "agriculturalActivitiesBusinessName",
    "agriculturalAssetsOtherFiscal",
    "agriculturalAssetsOtherPurchaseOrProductionCostsFiscalAmount",
    "agriculturalAssetsOtherResidualValueFiscal",
    "agriculturalEnterpriseType",
    "agriculturalStockOtherFiscal",
    "animalsFiscal",
    "animalsPurchaseOrProductionCostsFiscalAmount",
    "animalsResidualValueFiscal",
    "cartageFiscal",
    "demolitionInConnectionWithPurchaseOrDisposalLandToFarmerExists",
    "disposalLandInConnectionWithAgriculturalActivitiesExists",
    "disposalLandToFarmerExists",
    "disposalPropertiesExists",
    "disposalPropertiesFiscalReserveWriteOffExists",
    "fieldEquipmentFiscal",
    "flowerBulbsFiscal",
    "mushroomsFiscal",
    "nationalAgriculturalStandardsDeviationExists",
    "plantsAndSeedsAndStandsFiscal",
    "plantsAndSeedsAndStandsResidualValueFiscal",
    "plantsSeedsAndStandsPurchaseOrProductionCostsFiscalAmount",
    "productionRightsDepreciationFiscal",
    "productionRightsFiscal",
    "productionRightsPurchaseOrProductionCostsFiscal",
    "soilBelgiumOrGemanyExists",
    "stockAnimalsFiscal",
    "workThirdPartiesFiscal"
})
public class AgriculturalActivitiesSpecification
    extends Placeholder
{

    @XmlElement(name = "AgrarianNatureManagementSubsidyFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected NonNegativeMonetaryNoDecimalsItemType agrarianNatureManagementSubsidyFiscal;
    @XmlElement(name = "AgriculturalActivitiesBusinessName", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected Anstring70VItemType agriculturalActivitiesBusinessName;
    @XmlElement(name = "AgriculturalAssetsOtherFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected List<MonetaryNoDecimalsItemType> agriculturalAssetsOtherFiscal;
    @XmlElement(name = "AgriculturalAssetsOtherPurchaseOrProductionCostsFiscalAmount", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected MonetaryNoDecimalsItemType agriculturalAssetsOtherPurchaseOrProductionCostsFiscalAmount;
    @XmlElement(name = "AgriculturalAssetsOtherResidualValueFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected MonetaryNoDecimalsItemType agriculturalAssetsOtherResidualValueFiscal;
    @XmlElement(name = "AgriculturalEnterpriseType", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected Anstring70VItemType agriculturalEnterpriseType;
    @XmlElement(name = "AgriculturalStockOtherFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected List<MonetaryNoDecimalsItemType> agriculturalStockOtherFiscal;
    @XmlElement(name = "AnimalsFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected List<MonetaryNoDecimalsItemType> animalsFiscal;
    @XmlElement(name = "AnimalsPurchaseOrProductionCostsFiscalAmount", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected MonetaryNoDecimalsItemType animalsPurchaseOrProductionCostsFiscalAmount;
    @XmlElement(name = "AnimalsResidualValueFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected MonetaryNoDecimalsItemType animalsResidualValueFiscal;
    @XmlElement(name = "CartageFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected MonetaryNoDecimalsItemType cartageFiscal;
    @XmlElement(name = "DemolitionInConnectionWithPurchaseOrDisposalLandToFarmerExists", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected BooleanItemType demolitionInConnectionWithPurchaseOrDisposalLandToFarmerExists;
    @XmlElement(name = "DisposalLandInConnectionWithAgriculturalActivitiesExists", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected BooleanItemType disposalLandInConnectionWithAgriculturalActivitiesExists;
    @XmlElement(name = "DisposalLandToFarmerExists", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected BooleanItemType disposalLandToFarmerExists;
    @XmlElement(name = "DisposalPropertiesExists", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected BooleanItemType disposalPropertiesExists;
    @XmlElement(name = "DisposalPropertiesFiscalReserveWriteOffExists", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected BooleanItemType disposalPropertiesFiscalReserveWriteOffExists;
    @XmlElement(name = "FieldEquipmentFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected List<MonetaryNoDecimalsItemType> fieldEquipmentFiscal;
    @XmlElement(name = "FlowerBulbsFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected List<MonetaryNoDecimalsItemType> flowerBulbsFiscal;
    @XmlElement(name = "MushroomsFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected List<MonetaryNoDecimalsItemType> mushroomsFiscal;
    @XmlElement(name = "NationalAgriculturalStandardsDeviationExists", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected BooleanItemType nationalAgriculturalStandardsDeviationExists;
    @XmlElement(name = "PlantsAndSeedsAndStandsFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected List<MonetaryNoDecimalsItemType> plantsAndSeedsAndStandsFiscal;
    @XmlElement(name = "PlantsAndSeedsAndStandsResidualValueFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected MonetaryNoDecimalsItemType plantsAndSeedsAndStandsResidualValueFiscal;
    @XmlElement(name = "PlantsSeedsAndStandsPurchaseOrProductionCostsFiscalAmount", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected MonetaryNoDecimalsItemType plantsSeedsAndStandsPurchaseOrProductionCostsFiscalAmount;
    @XmlElement(name = "ProductionRightsDepreciationFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected NonNegativeMonetaryNoDecimalsItemType productionRightsDepreciationFiscal;
    @XmlElement(name = "ProductionRightsFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected List<NonNegativeMonetaryNoDecimalsItemType> productionRightsFiscal;
    @XmlElement(name = "ProductionRightsPurchaseOrProductionCostsFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected MonetaryNoDecimalsItemType productionRightsPurchaseOrProductionCostsFiscal;
    @XmlElement(name = "SoilBelgiumOrGemanyExists", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected BooleanItemType soilBelgiumOrGemanyExists;
    @XmlElement(name = "StockAnimalsFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected List<MonetaryNoDecimalsItemType> stockAnimalsFiscal;
    @XmlElement(name = "WorkThirdPartiesFiscal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected MonetaryNoDecimalsItemType workThirdPartiesFiscal;

    /**
     * Gets the value of the agrarianNatureManagementSubsidyFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getAgrarianNatureManagementSubsidyFiscal() {
        return agrarianNatureManagementSubsidyFiscal;
    }

    /**
     * Sets the value of the agrarianNatureManagementSubsidyFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setAgrarianNatureManagementSubsidyFiscal(NonNegativeMonetaryNoDecimalsItemType value) {
        this.agrarianNatureManagementSubsidyFiscal = value;
    }

    /**
     * Gets the value of the agriculturalActivitiesBusinessName property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring70VItemType }
     *     
     */
    public Anstring70VItemType getAgriculturalActivitiesBusinessName() {
        return agriculturalActivitiesBusinessName;
    }

    /**
     * Sets the value of the agriculturalActivitiesBusinessName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring70VItemType }
     *     
     */
    public void setAgriculturalActivitiesBusinessName(Anstring70VItemType value) {
        this.agriculturalActivitiesBusinessName = value;
    }

    /**
     * Gets the value of the agriculturalAssetsOtherFiscal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agriculturalAssetsOtherFiscal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgriculturalAssetsOtherFiscal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonetaryNoDecimalsItemType }
     * 
     * 
     */
    public List<MonetaryNoDecimalsItemType> getAgriculturalAssetsOtherFiscal() {
        if (agriculturalAssetsOtherFiscal == null) {
            agriculturalAssetsOtherFiscal = new ArrayList<MonetaryNoDecimalsItemType>();
        }
        return this.agriculturalAssetsOtherFiscal;
    }

    /**
     * Gets the value of the agriculturalAssetsOtherPurchaseOrProductionCostsFiscalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getAgriculturalAssetsOtherPurchaseOrProductionCostsFiscalAmount() {
        return agriculturalAssetsOtherPurchaseOrProductionCostsFiscalAmount;
    }

    /**
     * Sets the value of the agriculturalAssetsOtherPurchaseOrProductionCostsFiscalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setAgriculturalAssetsOtherPurchaseOrProductionCostsFiscalAmount(MonetaryNoDecimalsItemType value) {
        this.agriculturalAssetsOtherPurchaseOrProductionCostsFiscalAmount = value;
    }

    /**
     * Gets the value of the agriculturalAssetsOtherResidualValueFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getAgriculturalAssetsOtherResidualValueFiscal() {
        return agriculturalAssetsOtherResidualValueFiscal;
    }

    /**
     * Sets the value of the agriculturalAssetsOtherResidualValueFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setAgriculturalAssetsOtherResidualValueFiscal(MonetaryNoDecimalsItemType value) {
        this.agriculturalAssetsOtherResidualValueFiscal = value;
    }

    /**
     * Gets the value of the agriculturalEnterpriseType property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring70VItemType }
     *     
     */
    public Anstring70VItemType getAgriculturalEnterpriseType() {
        return agriculturalEnterpriseType;
    }

    /**
     * Sets the value of the agriculturalEnterpriseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring70VItemType }
     *     
     */
    public void setAgriculturalEnterpriseType(Anstring70VItemType value) {
        this.agriculturalEnterpriseType = value;
    }

    /**
     * Gets the value of the agriculturalStockOtherFiscal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agriculturalStockOtherFiscal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgriculturalStockOtherFiscal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonetaryNoDecimalsItemType }
     * 
     * 
     */
    public List<MonetaryNoDecimalsItemType> getAgriculturalStockOtherFiscal() {
        if (agriculturalStockOtherFiscal == null) {
            agriculturalStockOtherFiscal = new ArrayList<MonetaryNoDecimalsItemType>();
        }
        return this.agriculturalStockOtherFiscal;
    }

    /**
     * Gets the value of the animalsFiscal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the animalsFiscal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnimalsFiscal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonetaryNoDecimalsItemType }
     * 
     * 
     */
    public List<MonetaryNoDecimalsItemType> getAnimalsFiscal() {
        if (animalsFiscal == null) {
            animalsFiscal = new ArrayList<MonetaryNoDecimalsItemType>();
        }
        return this.animalsFiscal;
    }

    /**
     * Gets the value of the animalsPurchaseOrProductionCostsFiscalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getAnimalsPurchaseOrProductionCostsFiscalAmount() {
        return animalsPurchaseOrProductionCostsFiscalAmount;
    }

    /**
     * Sets the value of the animalsPurchaseOrProductionCostsFiscalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setAnimalsPurchaseOrProductionCostsFiscalAmount(MonetaryNoDecimalsItemType value) {
        this.animalsPurchaseOrProductionCostsFiscalAmount = value;
    }

    /**
     * Gets the value of the animalsResidualValueFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getAnimalsResidualValueFiscal() {
        return animalsResidualValueFiscal;
    }

    /**
     * Sets the value of the animalsResidualValueFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setAnimalsResidualValueFiscal(MonetaryNoDecimalsItemType value) {
        this.animalsResidualValueFiscal = value;
    }

    /**
     * Gets the value of the cartageFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getCartageFiscal() {
        return cartageFiscal;
    }

    /**
     * Sets the value of the cartageFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setCartageFiscal(MonetaryNoDecimalsItemType value) {
        this.cartageFiscal = value;
    }

    /**
     * Gets the value of the demolitionInConnectionWithPurchaseOrDisposalLandToFarmerExists property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getDemolitionInConnectionWithPurchaseOrDisposalLandToFarmerExists() {
        return demolitionInConnectionWithPurchaseOrDisposalLandToFarmerExists;
    }

    /**
     * Sets the value of the demolitionInConnectionWithPurchaseOrDisposalLandToFarmerExists property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setDemolitionInConnectionWithPurchaseOrDisposalLandToFarmerExists(BooleanItemType value) {
        this.demolitionInConnectionWithPurchaseOrDisposalLandToFarmerExists = value;
    }

    /**
     * Gets the value of the disposalLandInConnectionWithAgriculturalActivitiesExists property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getDisposalLandInConnectionWithAgriculturalActivitiesExists() {
        return disposalLandInConnectionWithAgriculturalActivitiesExists;
    }

    /**
     * Sets the value of the disposalLandInConnectionWithAgriculturalActivitiesExists property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setDisposalLandInConnectionWithAgriculturalActivitiesExists(BooleanItemType value) {
        this.disposalLandInConnectionWithAgriculturalActivitiesExists = value;
    }

    /**
     * Gets the value of the disposalLandToFarmerExists property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getDisposalLandToFarmerExists() {
        return disposalLandToFarmerExists;
    }

    /**
     * Sets the value of the disposalLandToFarmerExists property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setDisposalLandToFarmerExists(BooleanItemType value) {
        this.disposalLandToFarmerExists = value;
    }

    /**
     * Gets the value of the disposalPropertiesExists property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getDisposalPropertiesExists() {
        return disposalPropertiesExists;
    }

    /**
     * Sets the value of the disposalPropertiesExists property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setDisposalPropertiesExists(BooleanItemType value) {
        this.disposalPropertiesExists = value;
    }

    /**
     * Gets the value of the disposalPropertiesFiscalReserveWriteOffExists property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getDisposalPropertiesFiscalReserveWriteOffExists() {
        return disposalPropertiesFiscalReserveWriteOffExists;
    }

    /**
     * Sets the value of the disposalPropertiesFiscalReserveWriteOffExists property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setDisposalPropertiesFiscalReserveWriteOffExists(BooleanItemType value) {
        this.disposalPropertiesFiscalReserveWriteOffExists = value;
    }

    /**
     * Gets the value of the fieldEquipmentFiscal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldEquipmentFiscal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldEquipmentFiscal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonetaryNoDecimalsItemType }
     * 
     * 
     */
    public List<MonetaryNoDecimalsItemType> getFieldEquipmentFiscal() {
        if (fieldEquipmentFiscal == null) {
            fieldEquipmentFiscal = new ArrayList<MonetaryNoDecimalsItemType>();
        }
        return this.fieldEquipmentFiscal;
    }

    /**
     * Gets the value of the flowerBulbsFiscal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flowerBulbsFiscal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlowerBulbsFiscal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonetaryNoDecimalsItemType }
     * 
     * 
     */
    public List<MonetaryNoDecimalsItemType> getFlowerBulbsFiscal() {
        if (flowerBulbsFiscal == null) {
            flowerBulbsFiscal = new ArrayList<MonetaryNoDecimalsItemType>();
        }
        return this.flowerBulbsFiscal;
    }

    /**
     * Gets the value of the mushroomsFiscal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mushroomsFiscal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMushroomsFiscal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonetaryNoDecimalsItemType }
     * 
     * 
     */
    public List<MonetaryNoDecimalsItemType> getMushroomsFiscal() {
        if (mushroomsFiscal == null) {
            mushroomsFiscal = new ArrayList<MonetaryNoDecimalsItemType>();
        }
        return this.mushroomsFiscal;
    }

    /**
     * Gets the value of the nationalAgriculturalStandardsDeviationExists property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getNationalAgriculturalStandardsDeviationExists() {
        return nationalAgriculturalStandardsDeviationExists;
    }

    /**
     * Sets the value of the nationalAgriculturalStandardsDeviationExists property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setNationalAgriculturalStandardsDeviationExists(BooleanItemType value) {
        this.nationalAgriculturalStandardsDeviationExists = value;
    }

    /**
     * Gets the value of the plantsAndSeedsAndStandsFiscal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plantsAndSeedsAndStandsFiscal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlantsAndSeedsAndStandsFiscal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonetaryNoDecimalsItemType }
     * 
     * 
     */
    public List<MonetaryNoDecimalsItemType> getPlantsAndSeedsAndStandsFiscal() {
        if (plantsAndSeedsAndStandsFiscal == null) {
            plantsAndSeedsAndStandsFiscal = new ArrayList<MonetaryNoDecimalsItemType>();
        }
        return this.plantsAndSeedsAndStandsFiscal;
    }

    /**
     * Gets the value of the plantsAndSeedsAndStandsResidualValueFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getPlantsAndSeedsAndStandsResidualValueFiscal() {
        return plantsAndSeedsAndStandsResidualValueFiscal;
    }

    /**
     * Sets the value of the plantsAndSeedsAndStandsResidualValueFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setPlantsAndSeedsAndStandsResidualValueFiscal(MonetaryNoDecimalsItemType value) {
        this.plantsAndSeedsAndStandsResidualValueFiscal = value;
    }

    /**
     * Gets the value of the plantsSeedsAndStandsPurchaseOrProductionCostsFiscalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getPlantsSeedsAndStandsPurchaseOrProductionCostsFiscalAmount() {
        return plantsSeedsAndStandsPurchaseOrProductionCostsFiscalAmount;
    }

    /**
     * Sets the value of the plantsSeedsAndStandsPurchaseOrProductionCostsFiscalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setPlantsSeedsAndStandsPurchaseOrProductionCostsFiscalAmount(MonetaryNoDecimalsItemType value) {
        this.plantsSeedsAndStandsPurchaseOrProductionCostsFiscalAmount = value;
    }

    /**
     * Gets the value of the productionRightsDepreciationFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getProductionRightsDepreciationFiscal() {
        return productionRightsDepreciationFiscal;
    }

    /**
     * Sets the value of the productionRightsDepreciationFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setProductionRightsDepreciationFiscal(NonNegativeMonetaryNoDecimalsItemType value) {
        this.productionRightsDepreciationFiscal = value;
    }

    /**
     * Gets the value of the productionRightsFiscal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productionRightsFiscal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductionRightsFiscal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NonNegativeMonetaryNoDecimalsItemType }
     * 
     * 
     */
    public List<NonNegativeMonetaryNoDecimalsItemType> getProductionRightsFiscal() {
        if (productionRightsFiscal == null) {
            productionRightsFiscal = new ArrayList<NonNegativeMonetaryNoDecimalsItemType>();
        }
        return this.productionRightsFiscal;
    }

    /**
     * Gets the value of the productionRightsPurchaseOrProductionCostsFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getProductionRightsPurchaseOrProductionCostsFiscal() {
        return productionRightsPurchaseOrProductionCostsFiscal;
    }

    /**
     * Sets the value of the productionRightsPurchaseOrProductionCostsFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setProductionRightsPurchaseOrProductionCostsFiscal(MonetaryNoDecimalsItemType value) {
        this.productionRightsPurchaseOrProductionCostsFiscal = value;
    }

    /**
     * Gets the value of the soilBelgiumOrGemanyExists property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getSoilBelgiumOrGemanyExists() {
        return soilBelgiumOrGemanyExists;
    }

    /**
     * Sets the value of the soilBelgiumOrGemanyExists property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setSoilBelgiumOrGemanyExists(BooleanItemType value) {
        this.soilBelgiumOrGemanyExists = value;
    }

    /**
     * Gets the value of the stockAnimalsFiscal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stockAnimalsFiscal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStockAnimalsFiscal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonetaryNoDecimalsItemType }
     * 
     * 
     */
    public List<MonetaryNoDecimalsItemType> getStockAnimalsFiscal() {
        if (stockAnimalsFiscal == null) {
            stockAnimalsFiscal = new ArrayList<MonetaryNoDecimalsItemType>();
        }
        return this.stockAnimalsFiscal;
    }

    /**
     * Gets the value of the workThirdPartiesFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getWorkThirdPartiesFiscal() {
        return workThirdPartiesFiscal;
    }

    /**
     * Sets the value of the workThirdPartiesFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setWorkThirdPartiesFiscal(MonetaryNoDecimalsItemType value) {
        this.workThirdPartiesFiscal = value;
    }

}
