//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.10 at 11:10:53 AM CEST 
//


package nl.nltaxonomie.nt13.bd._20181212_b.dictionary.bd_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie.nt13.bd._20181212_b.dictionary.bd_types.Anstring20VItemType;
import nl.nltaxonomie.nt13.bd._20181212_b.dictionary.bd_types.Anstring34VItemType;
import nl.nltaxonomie.nt13.bd._20181212_b.dictionary.bd_types.Anstring70VItemType;
import nl.nltaxonomie.nt13.bd._20181212_b.dictionary.bd_types.NonNegativeInteger2FItemType;
import nl.nltaxonomie.nt13.bd._20181212_b.dictionary.bd_types.Perc32ItemType;
import nl.nltaxonomie.nt13.sbr._20180301.dictionary.nl_types.MonetaryNoDecimalsItemType;
import nl.nltaxonomie.nt13.sbr._20180301.dictionary.nl_types.NonNegativeMonetaryNoDecimalsItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}DebtOther" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}DebtOtherBalanceType" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}DebtOtherDescription" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}DebtOtherIdentificationNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}DebtOtherInterest" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}DebtOtherNominal" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data}DebtOtherProductID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "debtOther",
    "debtOtherBalanceType",
    "debtOtherDescription",
    "debtOtherIdentificationNumber",
    "debtOtherInterest",
    "debtOtherNominal",
    "debtOtherProductID"
})
public class DebtsOtherSpecification
    extends Placeholder
{

    @XmlElement(name = "DebtOther", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected NonNegativeMonetaryNoDecimalsItemType debtOther;
    @XmlElement(name = "DebtOtherBalanceType", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected NonNegativeInteger2FItemType debtOtherBalanceType;
    @XmlElement(name = "DebtOtherDescription", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected Anstring70VItemType debtOtherDescription;
    @XmlElement(name = "DebtOtherIdentificationNumber", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected Anstring34VItemType debtOtherIdentificationNumber;
    @XmlElement(name = "DebtOtherInterest", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected Perc32ItemType debtOtherInterest;
    @XmlElement(name = "DebtOtherNominal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected MonetaryNoDecimalsItemType debtOtherNominal;
    @XmlElement(name = "DebtOtherProductID", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212.b/dictionary/bd-data")
    protected Anstring20VItemType debtOtherProductID;

    /**
     * Gets the value of the debtOther property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getDebtOther() {
        return debtOther;
    }

    /**
     * Sets the value of the debtOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setDebtOther(NonNegativeMonetaryNoDecimalsItemType value) {
        this.debtOther = value;
    }

    /**
     * Gets the value of the debtOtherBalanceType property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeInteger2FItemType }
     *     
     */
    public NonNegativeInteger2FItemType getDebtOtherBalanceType() {
        return debtOtherBalanceType;
    }

    /**
     * Sets the value of the debtOtherBalanceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeInteger2FItemType }
     *     
     */
    public void setDebtOtherBalanceType(NonNegativeInteger2FItemType value) {
        this.debtOtherBalanceType = value;
    }

    /**
     * Gets the value of the debtOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring70VItemType }
     *     
     */
    public Anstring70VItemType getDebtOtherDescription() {
        return debtOtherDescription;
    }

    /**
     * Sets the value of the debtOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring70VItemType }
     *     
     */
    public void setDebtOtherDescription(Anstring70VItemType value) {
        this.debtOtherDescription = value;
    }

    /**
     * Gets the value of the debtOtherIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring34VItemType }
     *     
     */
    public Anstring34VItemType getDebtOtherIdentificationNumber() {
        return debtOtherIdentificationNumber;
    }

    /**
     * Sets the value of the debtOtherIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring34VItemType }
     *     
     */
    public void setDebtOtherIdentificationNumber(Anstring34VItemType value) {
        this.debtOtherIdentificationNumber = value;
    }

    /**
     * Gets the value of the debtOtherInterest property.
     * 
     * @return
     *     possible object is
     *     {@link Perc32ItemType }
     *     
     */
    public Perc32ItemType getDebtOtherInterest() {
        return debtOtherInterest;
    }

    /**
     * Sets the value of the debtOtherInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Perc32ItemType }
     *     
     */
    public void setDebtOtherInterest(Perc32ItemType value) {
        this.debtOtherInterest = value;
    }

    /**
     * Gets the value of the debtOtherNominal property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getDebtOtherNominal() {
        return debtOtherNominal;
    }

    /**
     * Sets the value of the debtOtherNominal property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setDebtOtherNominal(MonetaryNoDecimalsItemType value) {
        this.debtOtherNominal = value;
    }

    /**
     * Gets the value of the debtOtherProductID property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring20VItemType }
     *     
     */
    public Anstring20VItemType getDebtOtherProductID() {
        return debtOtherProductID;
    }

    /**
     * Sets the value of the debtOtherProductID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring20VItemType }
     *     
     */
    public void setDebtOtherProductID(Anstring20VItemType value) {
        this.debtOtherProductID = value;
    }

}
