//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.16 at 05:37:42 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(xmlns = { @XmlNs(prefix = "bd-dim-dim", namespaceURI = "http://www.nltaxonomie.nl/7.0/domein/bd/axes/bd-axes"),
		@XmlNs(prefix = "bd-dim-dom", namespaceURI = "http://www.nltaxonomie.nl/7.0/basis/bd/domains/bd-domains") }, namespace = "http://www.nltaxonomie.nl/7.0/basis/bd/types/bd-codes")
package nl.nltaxonomie._7_0.basis.bd.types.bd_codes;
import javax.xml.bind.annotation.XmlNs;

