//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.10 at 11:10:53 AM CEST 
//


package nl.nltaxonomie.nt13.bd._20190220_b.dictionary.bd_tuples_ext1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie.nt13.bd._20181212.dictionary.bd_tuples.AddressAbroadPresentation;
import nl.nltaxonomie.nt13.bd._20181212.dictionary.bd_tuples.AddressPresentation;
import nl.nltaxonomie.nt13.bd._20181212.dictionary.bd_types.Anstring10VItemType;
import nl.nltaxonomie.nt13.bd._20181212.dictionary.bd_types.Anstring200VItemType;
import nl.nltaxonomie.nt13.bd._20181212.dictionary.bd_types.MonetaryNoDecimals10VItemType;
import nl.nltaxonomie.nt13.bd._20181212.dictionary.bd_types.NonNegativeInteger6VItemType;
import nl.nltaxonomie.nt13.bd._20181212.dictionary.bd_types.Test11ItemType;
import nl.nltaxonomie.nt13.bd._20190220_b.dictionary.bd_codes_ext1.RelationCodeItemType;
import nl.nltaxonomie.nt13.bd._20190220_b.dictionary.bd_types_ext1.Anstring40VItemType;
import nl.nltaxonomie.nt13.bd._20190220_b.dictionary.bd_types_ext1.PositiveInteger6VItemType;
import nl.nltaxonomie.nt13.sbr._20180301.dictionary.nl_codes.GenderItemType;
import org.xbrl._2003.instance.BooleanItemType;
import org.xbrl._2003.instance.DateItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-tuples}AddressAbroadPresentation" minOccurs="0"/>
 *           &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-tuples}AddressPresentation" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryLegacyAcquisition" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataCohabitationAgreementCaregiverCareRecipient" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataCohabitationAgreementDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataDateOfBirth" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataDeferredPaymentHeirExposedProperty" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataGender" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataHeirIdenficationNumber"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataHeirInitials" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataHeirInstitutionName" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataHeirPrefix" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataHeirSurname" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataInheritancePercentageHeirDenominator"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataInheritancePercentageHeirNumerator"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataLegacyFreeFromRight" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataLegacyOtherTotal" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataPartnerIdentificationNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataRegistrationSameAdressInMonths" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataRegistrationSameAdressInYears" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataRelationCode"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataUsufruct" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1}HeirBenificiaryTaxedDataUsufructValue" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addressAbroadPresentation",
    "addressPresentation",
    "heirBenificiaryLegacyAcquisition",
    "heirBenificiaryTaxedDataCohabitationAgreementCaregiverCareRecipient",
    "heirBenificiaryTaxedDataCohabitationAgreementDate",
    "heirBenificiaryTaxedDataDateOfBirth",
    "heirBenificiaryTaxedDataDeferredPaymentHeirExposedProperty",
    "heirBenificiaryTaxedDataGender",
    "heirBenificiaryTaxedDataHeirIdenficationNumber",
    "heirBenificiaryTaxedDataHeirInitials",
    "heirBenificiaryTaxedDataHeirInstitutionName",
    "heirBenificiaryTaxedDataHeirPrefix",
    "heirBenificiaryTaxedDataHeirSurname",
    "heirBenificiaryTaxedDataInheritancePercentageHeirDenominator",
    "heirBenificiaryTaxedDataInheritancePercentageHeirNumerator",
    "heirBenificiaryTaxedDataLegacyFreeFromRight",
    "heirBenificiaryTaxedDataLegacyOtherTotal",
    "heirBenificiaryTaxedDataPartnerIdentificationNumber",
    "heirBenificiaryTaxedDataRegistrationSameAdressInMonths",
    "heirBenificiaryTaxedDataRegistrationSameAdressInYears",
    "heirBenificiaryTaxedDataRelationCode",
    "heirBenificiaryTaxedDataUsufruct",
    "heirBenificiaryTaxedDataUsufructValue"
})
public class HeirBenificiaryTaxedDataSpecification
    extends Placeholder
{

    @XmlElement(name = "AddressAbroadPresentation", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-tuples")
    protected AddressAbroadPresentation addressAbroadPresentation;
    @XmlElement(name = "AddressPresentation", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-tuples")
    protected AddressPresentation addressPresentation;
    @XmlElement(name = "HeirBenificiaryLegacyAcquisition", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected BooleanItemType heirBenificiaryLegacyAcquisition;
    @XmlElement(name = "HeirBenificiaryTaxedDataCohabitationAgreementCaregiverCareRecipient", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected BooleanItemType heirBenificiaryTaxedDataCohabitationAgreementCaregiverCareRecipient;
    @XmlElement(name = "HeirBenificiaryTaxedDataCohabitationAgreementDate", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected DateItemType heirBenificiaryTaxedDataCohabitationAgreementDate;
    @XmlElement(name = "HeirBenificiaryTaxedDataDateOfBirth", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected DateItemType heirBenificiaryTaxedDataDateOfBirth;
    @XmlElement(name = "HeirBenificiaryTaxedDataDeferredPaymentHeirExposedProperty", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected BooleanItemType heirBenificiaryTaxedDataDeferredPaymentHeirExposedProperty;
    @XmlElement(name = "HeirBenificiaryTaxedDataGender", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected GenderItemType heirBenificiaryTaxedDataGender;
    @XmlElement(name = "HeirBenificiaryTaxedDataHeirIdenficationNumber", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1", required = true)
    protected Test11ItemType heirBenificiaryTaxedDataHeirIdenficationNumber;
    @XmlElement(name = "HeirBenificiaryTaxedDataHeirInitials", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected Anstring10VItemType heirBenificiaryTaxedDataHeirInitials;
    @XmlElement(name = "HeirBenificiaryTaxedDataHeirInstitutionName", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected Anstring40VItemType heirBenificiaryTaxedDataHeirInstitutionName;
    @XmlElement(name = "HeirBenificiaryTaxedDataHeirPrefix", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected Anstring10VItemType heirBenificiaryTaxedDataHeirPrefix;
    @XmlElement(name = "HeirBenificiaryTaxedDataHeirSurname", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected Anstring200VItemType heirBenificiaryTaxedDataHeirSurname;
    @XmlElement(name = "HeirBenificiaryTaxedDataInheritancePercentageHeirDenominator", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1", required = true)
    protected PositiveInteger6VItemType heirBenificiaryTaxedDataInheritancePercentageHeirDenominator;
    @XmlElement(name = "HeirBenificiaryTaxedDataInheritancePercentageHeirNumerator", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1", required = true)
    protected NonNegativeInteger6VItemType heirBenificiaryTaxedDataInheritancePercentageHeirNumerator;
    @XmlElement(name = "HeirBenificiaryTaxedDataLegacyFreeFromRight", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected MonetaryNoDecimals10VItemType heirBenificiaryTaxedDataLegacyFreeFromRight;
    @XmlElement(name = "HeirBenificiaryTaxedDataLegacyOtherTotal", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected MonetaryNoDecimals10VItemType heirBenificiaryTaxedDataLegacyOtherTotal;
    @XmlElement(name = "HeirBenificiaryTaxedDataPartnerIdentificationNumber", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected Test11ItemType heirBenificiaryTaxedDataPartnerIdentificationNumber;
    @XmlElement(name = "HeirBenificiaryTaxedDataRegistrationSameAdressInMonths", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected BooleanItemType heirBenificiaryTaxedDataRegistrationSameAdressInMonths;
    @XmlElement(name = "HeirBenificiaryTaxedDataRegistrationSameAdressInYears", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected BooleanItemType heirBenificiaryTaxedDataRegistrationSameAdressInYears;
    @XmlElement(name = "HeirBenificiaryTaxedDataRelationCode", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1", required = true)
    protected RelationCodeItemType heirBenificiaryTaxedDataRelationCode;
    @XmlElement(name = "HeirBenificiaryTaxedDataUsufruct", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected BooleanItemType heirBenificiaryTaxedDataUsufruct;
    @XmlElement(name = "HeirBenificiaryTaxedDataUsufructValue", namespace = "http://www.nltaxonomie.nl/nt13/bd/20190220.b/dictionary/bd-data-ext1")
    protected MonetaryNoDecimals10VItemType heirBenificiaryTaxedDataUsufructValue;

    /**
     * Gets the value of the addressAbroadPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link AddressAbroadPresentation }
     *     
     */
    public AddressAbroadPresentation getAddressAbroadPresentation() {
        return addressAbroadPresentation;
    }

    /**
     * Sets the value of the addressAbroadPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressAbroadPresentation }
     *     
     */
    public void setAddressAbroadPresentation(AddressAbroadPresentation value) {
        this.addressAbroadPresentation = value;
    }

    /**
     * Gets the value of the addressPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link AddressPresentation }
     *     
     */
    public AddressPresentation getAddressPresentation() {
        return addressPresentation;
    }

    /**
     * Sets the value of the addressPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressPresentation }
     *     
     */
    public void setAddressPresentation(AddressPresentation value) {
        this.addressPresentation = value;
    }

    /**
     * Gets the value of the heirBenificiaryLegacyAcquisition property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getHeirBenificiaryLegacyAcquisition() {
        return heirBenificiaryLegacyAcquisition;
    }

    /**
     * Sets the value of the heirBenificiaryLegacyAcquisition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setHeirBenificiaryLegacyAcquisition(BooleanItemType value) {
        this.heirBenificiaryLegacyAcquisition = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataCohabitationAgreementCaregiverCareRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getHeirBenificiaryTaxedDataCohabitationAgreementCaregiverCareRecipient() {
        return heirBenificiaryTaxedDataCohabitationAgreementCaregiverCareRecipient;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataCohabitationAgreementCaregiverCareRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataCohabitationAgreementCaregiverCareRecipient(BooleanItemType value) {
        this.heirBenificiaryTaxedDataCohabitationAgreementCaregiverCareRecipient = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataCohabitationAgreementDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateItemType }
     *     
     */
    public DateItemType getHeirBenificiaryTaxedDataCohabitationAgreementDate() {
        return heirBenificiaryTaxedDataCohabitationAgreementDate;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataCohabitationAgreementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataCohabitationAgreementDate(DateItemType value) {
        this.heirBenificiaryTaxedDataCohabitationAgreementDate = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataDateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link DateItemType }
     *     
     */
    public DateItemType getHeirBenificiaryTaxedDataDateOfBirth() {
        return heirBenificiaryTaxedDataDateOfBirth;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataDateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataDateOfBirth(DateItemType value) {
        this.heirBenificiaryTaxedDataDateOfBirth = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataDeferredPaymentHeirExposedProperty property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getHeirBenificiaryTaxedDataDeferredPaymentHeirExposedProperty() {
        return heirBenificiaryTaxedDataDeferredPaymentHeirExposedProperty;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataDeferredPaymentHeirExposedProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataDeferredPaymentHeirExposedProperty(BooleanItemType value) {
        this.heirBenificiaryTaxedDataDeferredPaymentHeirExposedProperty = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataGender property.
     * 
     * @return
     *     possible object is
     *     {@link GenderItemType }
     *     
     */
    public GenderItemType getHeirBenificiaryTaxedDataGender() {
        return heirBenificiaryTaxedDataGender;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataGender property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenderItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataGender(GenderItemType value) {
        this.heirBenificiaryTaxedDataGender = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataHeirIdenficationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Test11ItemType }
     *     
     */
    public Test11ItemType getHeirBenificiaryTaxedDataHeirIdenficationNumber() {
        return heirBenificiaryTaxedDataHeirIdenficationNumber;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataHeirIdenficationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Test11ItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataHeirIdenficationNumber(Test11ItemType value) {
        this.heirBenificiaryTaxedDataHeirIdenficationNumber = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataHeirInitials property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring10VItemType }
     *     
     */
    public Anstring10VItemType getHeirBenificiaryTaxedDataHeirInitials() {
        return heirBenificiaryTaxedDataHeirInitials;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataHeirInitials property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring10VItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataHeirInitials(Anstring10VItemType value) {
        this.heirBenificiaryTaxedDataHeirInitials = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataHeirInstitutionName property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring40VItemType }
     *     
     */
    public Anstring40VItemType getHeirBenificiaryTaxedDataHeirInstitutionName() {
        return heirBenificiaryTaxedDataHeirInstitutionName;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataHeirInstitutionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring40VItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataHeirInstitutionName(Anstring40VItemType value) {
        this.heirBenificiaryTaxedDataHeirInstitutionName = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataHeirPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring10VItemType }
     *     
     */
    public Anstring10VItemType getHeirBenificiaryTaxedDataHeirPrefix() {
        return heirBenificiaryTaxedDataHeirPrefix;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataHeirPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring10VItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataHeirPrefix(Anstring10VItemType value) {
        this.heirBenificiaryTaxedDataHeirPrefix = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataHeirSurname property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring200VItemType }
     *     
     */
    public Anstring200VItemType getHeirBenificiaryTaxedDataHeirSurname() {
        return heirBenificiaryTaxedDataHeirSurname;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataHeirSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring200VItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataHeirSurname(Anstring200VItemType value) {
        this.heirBenificiaryTaxedDataHeirSurname = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataInheritancePercentageHeirDenominator property.
     * 
     * @return
     *     possible object is
     *     {@link PositiveInteger6VItemType }
     *     
     */
    public PositiveInteger6VItemType getHeirBenificiaryTaxedDataInheritancePercentageHeirDenominator() {
        return heirBenificiaryTaxedDataInheritancePercentageHeirDenominator;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataInheritancePercentageHeirDenominator property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositiveInteger6VItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataInheritancePercentageHeirDenominator(PositiveInteger6VItemType value) {
        this.heirBenificiaryTaxedDataInheritancePercentageHeirDenominator = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataInheritancePercentageHeirNumerator property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeInteger6VItemType }
     *     
     */
    public NonNegativeInteger6VItemType getHeirBenificiaryTaxedDataInheritancePercentageHeirNumerator() {
        return heirBenificiaryTaxedDataInheritancePercentageHeirNumerator;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataInheritancePercentageHeirNumerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeInteger6VItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataInheritancePercentageHeirNumerator(NonNegativeInteger6VItemType value) {
        this.heirBenificiaryTaxedDataInheritancePercentageHeirNumerator = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataLegacyFreeFromRight property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getHeirBenificiaryTaxedDataLegacyFreeFromRight() {
        return heirBenificiaryTaxedDataLegacyFreeFromRight;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataLegacyFreeFromRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataLegacyFreeFromRight(MonetaryNoDecimals10VItemType value) {
        this.heirBenificiaryTaxedDataLegacyFreeFromRight = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataLegacyOtherTotal property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getHeirBenificiaryTaxedDataLegacyOtherTotal() {
        return heirBenificiaryTaxedDataLegacyOtherTotal;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataLegacyOtherTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataLegacyOtherTotal(MonetaryNoDecimals10VItemType value) {
        this.heirBenificiaryTaxedDataLegacyOtherTotal = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataPartnerIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Test11ItemType }
     *     
     */
    public Test11ItemType getHeirBenificiaryTaxedDataPartnerIdentificationNumber() {
        return heirBenificiaryTaxedDataPartnerIdentificationNumber;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataPartnerIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Test11ItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataPartnerIdentificationNumber(Test11ItemType value) {
        this.heirBenificiaryTaxedDataPartnerIdentificationNumber = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataRegistrationSameAdressInMonths property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getHeirBenificiaryTaxedDataRegistrationSameAdressInMonths() {
        return heirBenificiaryTaxedDataRegistrationSameAdressInMonths;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataRegistrationSameAdressInMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataRegistrationSameAdressInMonths(BooleanItemType value) {
        this.heirBenificiaryTaxedDataRegistrationSameAdressInMonths = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataRegistrationSameAdressInYears property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getHeirBenificiaryTaxedDataRegistrationSameAdressInYears() {
        return heirBenificiaryTaxedDataRegistrationSameAdressInYears;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataRegistrationSameAdressInYears property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataRegistrationSameAdressInYears(BooleanItemType value) {
        this.heirBenificiaryTaxedDataRegistrationSameAdressInYears = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataRelationCode property.
     * 
     * @return
     *     possible object is
     *     {@link RelationCodeItemType }
     *     
     */
    public RelationCodeItemType getHeirBenificiaryTaxedDataRelationCode() {
        return heirBenificiaryTaxedDataRelationCode;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataRelationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationCodeItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataRelationCode(RelationCodeItemType value) {
        this.heirBenificiaryTaxedDataRelationCode = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataUsufruct property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getHeirBenificiaryTaxedDataUsufruct() {
        return heirBenificiaryTaxedDataUsufruct;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataUsufruct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataUsufruct(BooleanItemType value) {
        this.heirBenificiaryTaxedDataUsufruct = value;
    }

    /**
     * Gets the value of the heirBenificiaryTaxedDataUsufructValue property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getHeirBenificiaryTaxedDataUsufructValue() {
        return heirBenificiaryTaxedDataUsufructValue;
    }

    /**
     * Sets the value of the heirBenificiaryTaxedDataUsufructValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setHeirBenificiaryTaxedDataUsufructValue(MonetaryNoDecimals10VItemType value) {
        this.heirBenificiaryTaxedDataUsufructValue = value;
    }

}
