//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.25 at 08:13:42 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nltaxonomie.nl/9.0/basis/sbr/types/nl-codes")
package nl.nltaxonomie._9_0.basis.sbr.types.nl_codes;
