//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 09:06:01 PM CET 
//


package nl.nltaxonomie._7_0_b_1.domein.bd.tuples.bd_ob_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie._7_0_b_1.basis.bd.types.bd_types.ACAPITALstring4FItemType;
import nl.nltaxonomie._7_0_b_1.basis.bd.types.bd_types.Anstring2FItemType;
import nl.nltaxonomie._7_0_b_1.basis.bd.types.bd_types.DateTimeItemType;
import nl.nltaxonomie._7_0_b_1.basis.bd.types.bd_types.MessageReferenceSupplierVATItemType;
import nl.nltaxonomie._7_0_b_1.basis.bd.types.bd_types.MonetaryNoDecimals10VItemType;
import nl.nltaxonomie._7_0_b_1.basis.bd.types.bd_types.MonetaryNoDecimals4VItemType;
import nl.nltaxonomie._7_0_b_1.basis.bd.types.bd_types.MonetaryNoDecimals9VItemType;
import nl.nltaxonomie._7_0_b_1.domein.bd.tuples.bd_alg_tuples.CorrespondentConsultantAdvisor;
import nl.nltaxonomie._7_0_b_1.domein.bd.tuples.bd_alg_tuples.CorrespondentDeclarant;
import nl.nltaxonomie._7_0_b_1.domein.bd.tuples.bd_alg_tuples.CorrespondentServicebureau;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/domein/bd/tuples/bd-alg-tuples}CorrespondentConsultantAdvisor" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/domein/bd/tuples/bd-alg-tuples}CorrespondentDeclarant" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/domein/bd/tuples/bd-alg-tuples}CorrespondentServicebureau" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-algemeen}DateTimeCreation"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}EstimateFromPreviousReturns" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}EstimateOnThisReturn" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}InstallationDistanceSalesWithinTheEC" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-algemeen}MessageReferenceSupplierVAT"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}SmallEntrepreneurProvisionReduction" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-algemeen}SoftwareSupplierCode"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}SuppliesServicesNotTaxed" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}SuppliesToCountriesOutsideTheEC" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}SuppliesToCountriesWithinTheEC" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}TaxedTurnoverPrivateUse" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}TaxedTurnoverSuppliesServicesGeneralTariff" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}TaxedTurnoverSuppliesServicesOtherRates" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}TaxedTurnoverSuppliesServicesReducedTariff" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}TurnoverFromTaxedSuppliesFromCountriesOutsideTheEC" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}TurnoverFromTaxedSuppliesFromCountriesWithinTheEC" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}TurnoverSuppliesServicesByWhichVATTaxationIsTransferred" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}ValueAddedTaxOnInput" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}ValueAddedTaxOnSuppliesFromCountriesOutsideTheEC" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}ValueAddedTaxOnSuppliesFromCountriesWithinTheEC" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}ValueAddedTaxOwed"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}ValueAddedTaxOwedToBePaidBack"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}ValueAddedTaxPrivateUse" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}ValueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}ValueAddedTaxSuppliesServicesGeneralTariff" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}ValueAddedTaxSuppliesServicesOtherRates" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting}ValueAddedTaxSuppliesServicesReducedTariff" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-algemeen}VersionApplication"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "correspondentConsultantAdvisor",
    "correspondentDeclarant",
    "correspondentServicebureau",
    "dateTimeCreation",
    "estimateFromPreviousReturns",
    "estimateOnThisReturn",
    "installationDistanceSalesWithinTheEC",
    "messageReferenceSupplierVAT",
    "smallEntrepreneurProvisionReduction",
    "softwareSupplierCode",
    "suppliesServicesNotTaxed",
    "suppliesToCountriesOutsideTheEC",
    "suppliesToCountriesWithinTheEC",
    "taxedTurnoverPrivateUse",
    "taxedTurnoverSuppliesServicesGeneralTariff",
    "taxedTurnoverSuppliesServicesOtherRates",
    "taxedTurnoverSuppliesServicesReducedTariff",
    "turnoverFromTaxedSuppliesFromCountriesOutsideTheEC",
    "turnoverFromTaxedSuppliesFromCountriesWithinTheEC",
    "turnoverSuppliesServicesByWhichVATTaxationIsTransferred",
    "valueAddedTaxOnInput",
    "valueAddedTaxOnSuppliesFromCountriesOutsideTheEC",
    "valueAddedTaxOnSuppliesFromCountriesWithinTheEC",
    "valueAddedTaxOwed",
    "valueAddedTaxOwedToBePaidBack",
    "valueAddedTaxPrivateUse",
    "valueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred",
    "valueAddedTaxSuppliesServicesGeneralTariff",
    "valueAddedTaxSuppliesServicesOtherRates",
    "valueAddedTaxSuppliesServicesReducedTariff",
    "versionApplication"
})
public class ValueAddedTaxDeclaration
    extends Placeholder
{

    @XmlElement(name = "CorrespondentConsultantAdvisor", namespace = "http://www.nltaxonomie.nl/7.0.b.1/domein/bd/tuples/bd-alg-tuples")
    protected CorrespondentConsultantAdvisor correspondentConsultantAdvisor;
    @XmlElement(name = "CorrespondentDeclarant", namespace = "http://www.nltaxonomie.nl/7.0.b.1/domein/bd/tuples/bd-alg-tuples")
    protected CorrespondentDeclarant correspondentDeclarant;
    @XmlElement(name = "CorrespondentServicebureau", namespace = "http://www.nltaxonomie.nl/7.0.b.1/domein/bd/tuples/bd-alg-tuples")
    protected CorrespondentServicebureau correspondentServicebureau;
    @XmlElement(name = "DateTimeCreation", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-algemeen", required = true)
    protected DateTimeItemType dateTimeCreation;
    @XmlElement(name = "EstimateFromPreviousReturns", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals9VItemType estimateFromPreviousReturns;
    @XmlElement(name = "EstimateOnThisReturn", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals9VItemType estimateOnThisReturn;
    @XmlElement(name = "InstallationDistanceSalesWithinTheEC", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals10VItemType installationDistanceSalesWithinTheEC;
    @XmlElement(name = "MessageReferenceSupplierVAT", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-algemeen", required = true)
    protected MessageReferenceSupplierVATItemType messageReferenceSupplierVAT;
    @XmlElement(name = "SmallEntrepreneurProvisionReduction", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals4VItemType smallEntrepreneurProvisionReduction;
    @XmlElement(name = "SoftwareSupplierCode", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-algemeen", required = true)
    protected ACAPITALstring4FItemType softwareSupplierCode;
    @XmlElement(name = "SuppliesServicesNotTaxed", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals10VItemType suppliesServicesNotTaxed;
    @XmlElement(name = "SuppliesToCountriesOutsideTheEC", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals10VItemType suppliesToCountriesOutsideTheEC;
    @XmlElement(name = "SuppliesToCountriesWithinTheEC", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals10VItemType suppliesToCountriesWithinTheEC;
    @XmlElement(name = "TaxedTurnoverPrivateUse", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals10VItemType taxedTurnoverPrivateUse;
    @XmlElement(name = "TaxedTurnoverSuppliesServicesGeneralTariff", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals10VItemType taxedTurnoverSuppliesServicesGeneralTariff;
    @XmlElement(name = "TaxedTurnoverSuppliesServicesOtherRates", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals10VItemType taxedTurnoverSuppliesServicesOtherRates;
    @XmlElement(name = "TaxedTurnoverSuppliesServicesReducedTariff", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals10VItemType taxedTurnoverSuppliesServicesReducedTariff;
    @XmlElement(name = "TurnoverFromTaxedSuppliesFromCountriesOutsideTheEC", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals10VItemType turnoverFromTaxedSuppliesFromCountriesOutsideTheEC;
    @XmlElement(name = "TurnoverFromTaxedSuppliesFromCountriesWithinTheEC", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals10VItemType turnoverFromTaxedSuppliesFromCountriesWithinTheEC;
    @XmlElement(name = "TurnoverSuppliesServicesByWhichVATTaxationIsTransferred", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals10VItemType turnoverSuppliesServicesByWhichVATTaxationIsTransferred;
    @XmlElement(name = "ValueAddedTaxOnInput", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals10VItemType valueAddedTaxOnInput;
    @XmlElement(name = "ValueAddedTaxOnSuppliesFromCountriesOutsideTheEC", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals9VItemType valueAddedTaxOnSuppliesFromCountriesOutsideTheEC;
    @XmlElement(name = "ValueAddedTaxOnSuppliesFromCountriesWithinTheEC", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals9VItemType valueAddedTaxOnSuppliesFromCountriesWithinTheEC;
    @XmlElement(name = "ValueAddedTaxOwed", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting", required = true)
    protected MonetaryNoDecimals10VItemType valueAddedTaxOwed;
    @XmlElement(name = "ValueAddedTaxOwedToBePaidBack", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting", required = true)
    protected MonetaryNoDecimals9VItemType valueAddedTaxOwedToBePaidBack;
    @XmlElement(name = "ValueAddedTaxPrivateUse", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals9VItemType valueAddedTaxPrivateUse;
    @XmlElement(name = "ValueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals9VItemType valueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred;
    @XmlElement(name = "ValueAddedTaxSuppliesServicesGeneralTariff", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals9VItemType valueAddedTaxSuppliesServicesGeneralTariff;
    @XmlElement(name = "ValueAddedTaxSuppliesServicesOtherRates", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals9VItemType valueAddedTaxSuppliesServicesOtherRates;
    @XmlElement(name = "ValueAddedTaxSuppliesServicesReducedTariff", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-omzetbelasting")
    protected MonetaryNoDecimals9VItemType valueAddedTaxSuppliesServicesReducedTariff;
    @XmlElement(name = "VersionApplication", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-algemeen", required = true)
    protected Anstring2FItemType versionApplication;

    /**
     * Gets the value of the correspondentConsultantAdvisor property.
     * 
     * @return
     *     possible object is
     *     {@link CorrespondentConsultantAdvisor }
     *     
     */
    public CorrespondentConsultantAdvisor getCorrespondentConsultantAdvisor() {
        return correspondentConsultantAdvisor;
    }

    /**
     * Sets the value of the correspondentConsultantAdvisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrespondentConsultantAdvisor }
     *     
     */
    public void setCorrespondentConsultantAdvisor(CorrespondentConsultantAdvisor value) {
        this.correspondentConsultantAdvisor = value;
    }

    /**
     * Gets the value of the correspondentDeclarant property.
     * 
     * @return
     *     possible object is
     *     {@link CorrespondentDeclarant }
     *     
     */
    public CorrespondentDeclarant getCorrespondentDeclarant() {
        return correspondentDeclarant;
    }

    /**
     * Sets the value of the correspondentDeclarant property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrespondentDeclarant }
     *     
     */
    public void setCorrespondentDeclarant(CorrespondentDeclarant value) {
        this.correspondentDeclarant = value;
    }

    /**
     * Gets the value of the correspondentServicebureau property.
     * 
     * @return
     *     possible object is
     *     {@link CorrespondentServicebureau }
     *     
     */
    public CorrespondentServicebureau getCorrespondentServicebureau() {
        return correspondentServicebureau;
    }

    /**
     * Sets the value of the correspondentServicebureau property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrespondentServicebureau }
     *     
     */
    public void setCorrespondentServicebureau(CorrespondentServicebureau value) {
        this.correspondentServicebureau = value;
    }

    /**
     * Gets the value of the dateTimeCreation property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeItemType }
     *     
     */
    public DateTimeItemType getDateTimeCreation() {
        return dateTimeCreation;
    }

    /**
     * Sets the value of the dateTimeCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeItemType }
     *     
     */
    public void setDateTimeCreation(DateTimeItemType value) {
        this.dateTimeCreation = value;
    }

    /**
     * Gets the value of the estimateFromPreviousReturns property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public MonetaryNoDecimals9VItemType getEstimateFromPreviousReturns() {
        return estimateFromPreviousReturns;
    }

    /**
     * Sets the value of the estimateFromPreviousReturns property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public void setEstimateFromPreviousReturns(MonetaryNoDecimals9VItemType value) {
        this.estimateFromPreviousReturns = value;
    }

    /**
     * Gets the value of the estimateOnThisReturn property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public MonetaryNoDecimals9VItemType getEstimateOnThisReturn() {
        return estimateOnThisReturn;
    }

    /**
     * Sets the value of the estimateOnThisReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public void setEstimateOnThisReturn(MonetaryNoDecimals9VItemType value) {
        this.estimateOnThisReturn = value;
    }

    /**
     * Gets the value of the installationDistanceSalesWithinTheEC property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getInstallationDistanceSalesWithinTheEC() {
        return installationDistanceSalesWithinTheEC;
    }

    /**
     * Sets the value of the installationDistanceSalesWithinTheEC property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setInstallationDistanceSalesWithinTheEC(MonetaryNoDecimals10VItemType value) {
        this.installationDistanceSalesWithinTheEC = value;
    }

    /**
     * Gets the value of the messageReferenceSupplierVAT property.
     * 
     * @return
     *     possible object is
     *     {@link MessageReferenceSupplierVATItemType }
     *     
     */
    public MessageReferenceSupplierVATItemType getMessageReferenceSupplierVAT() {
        return messageReferenceSupplierVAT;
    }

    /**
     * Sets the value of the messageReferenceSupplierVAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageReferenceSupplierVATItemType }
     *     
     */
    public void setMessageReferenceSupplierVAT(MessageReferenceSupplierVATItemType value) {
        this.messageReferenceSupplierVAT = value;
    }

    /**
     * Gets the value of the smallEntrepreneurProvisionReduction property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals4VItemType }
     *     
     */
    public MonetaryNoDecimals4VItemType getSmallEntrepreneurProvisionReduction() {
        return smallEntrepreneurProvisionReduction;
    }

    /**
     * Sets the value of the smallEntrepreneurProvisionReduction property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals4VItemType }
     *     
     */
    public void setSmallEntrepreneurProvisionReduction(MonetaryNoDecimals4VItemType value) {
        this.smallEntrepreneurProvisionReduction = value;
    }

    /**
     * Gets the value of the softwareSupplierCode property.
     * 
     * @return
     *     possible object is
     *     {@link ACAPITALstring4FItemType }
     *     
     */
    public ACAPITALstring4FItemType getSoftwareSupplierCode() {
        return softwareSupplierCode;
    }

    /**
     * Sets the value of the softwareSupplierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACAPITALstring4FItemType }
     *     
     */
    public void setSoftwareSupplierCode(ACAPITALstring4FItemType value) {
        this.softwareSupplierCode = value;
    }

    /**
     * Gets the value of the suppliesServicesNotTaxed property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getSuppliesServicesNotTaxed() {
        return suppliesServicesNotTaxed;
    }

    /**
     * Sets the value of the suppliesServicesNotTaxed property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setSuppliesServicesNotTaxed(MonetaryNoDecimals10VItemType value) {
        this.suppliesServicesNotTaxed = value;
    }

    /**
     * Gets the value of the suppliesToCountriesOutsideTheEC property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getSuppliesToCountriesOutsideTheEC() {
        return suppliesToCountriesOutsideTheEC;
    }

    /**
     * Sets the value of the suppliesToCountriesOutsideTheEC property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setSuppliesToCountriesOutsideTheEC(MonetaryNoDecimals10VItemType value) {
        this.suppliesToCountriesOutsideTheEC = value;
    }

    /**
     * Gets the value of the suppliesToCountriesWithinTheEC property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getSuppliesToCountriesWithinTheEC() {
        return suppliesToCountriesWithinTheEC;
    }

    /**
     * Sets the value of the suppliesToCountriesWithinTheEC property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setSuppliesToCountriesWithinTheEC(MonetaryNoDecimals10VItemType value) {
        this.suppliesToCountriesWithinTheEC = value;
    }

    /**
     * Gets the value of the taxedTurnoverPrivateUse property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getTaxedTurnoverPrivateUse() {
        return taxedTurnoverPrivateUse;
    }

    /**
     * Sets the value of the taxedTurnoverPrivateUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setTaxedTurnoverPrivateUse(MonetaryNoDecimals10VItemType value) {
        this.taxedTurnoverPrivateUse = value;
    }

    /**
     * Gets the value of the taxedTurnoverSuppliesServicesGeneralTariff property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getTaxedTurnoverSuppliesServicesGeneralTariff() {
        return taxedTurnoverSuppliesServicesGeneralTariff;
    }

    /**
     * Sets the value of the taxedTurnoverSuppliesServicesGeneralTariff property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setTaxedTurnoverSuppliesServicesGeneralTariff(MonetaryNoDecimals10VItemType value) {
        this.taxedTurnoverSuppliesServicesGeneralTariff = value;
    }

    /**
     * Gets the value of the taxedTurnoverSuppliesServicesOtherRates property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getTaxedTurnoverSuppliesServicesOtherRates() {
        return taxedTurnoverSuppliesServicesOtherRates;
    }

    /**
     * Sets the value of the taxedTurnoverSuppliesServicesOtherRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setTaxedTurnoverSuppliesServicesOtherRates(MonetaryNoDecimals10VItemType value) {
        this.taxedTurnoverSuppliesServicesOtherRates = value;
    }

    /**
     * Gets the value of the taxedTurnoverSuppliesServicesReducedTariff property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getTaxedTurnoverSuppliesServicesReducedTariff() {
        return taxedTurnoverSuppliesServicesReducedTariff;
    }

    /**
     * Sets the value of the taxedTurnoverSuppliesServicesReducedTariff property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setTaxedTurnoverSuppliesServicesReducedTariff(MonetaryNoDecimals10VItemType value) {
        this.taxedTurnoverSuppliesServicesReducedTariff = value;
    }

    /**
     * Gets the value of the turnoverFromTaxedSuppliesFromCountriesOutsideTheEC property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getTurnoverFromTaxedSuppliesFromCountriesOutsideTheEC() {
        return turnoverFromTaxedSuppliesFromCountriesOutsideTheEC;
    }

    /**
     * Sets the value of the turnoverFromTaxedSuppliesFromCountriesOutsideTheEC property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setTurnoverFromTaxedSuppliesFromCountriesOutsideTheEC(MonetaryNoDecimals10VItemType value) {
        this.turnoverFromTaxedSuppliesFromCountriesOutsideTheEC = value;
    }

    /**
     * Gets the value of the turnoverFromTaxedSuppliesFromCountriesWithinTheEC property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getTurnoverFromTaxedSuppliesFromCountriesWithinTheEC() {
        return turnoverFromTaxedSuppliesFromCountriesWithinTheEC;
    }

    /**
     * Sets the value of the turnoverFromTaxedSuppliesFromCountriesWithinTheEC property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setTurnoverFromTaxedSuppliesFromCountriesWithinTheEC(MonetaryNoDecimals10VItemType value) {
        this.turnoverFromTaxedSuppliesFromCountriesWithinTheEC = value;
    }

    /**
     * Gets the value of the turnoverSuppliesServicesByWhichVATTaxationIsTransferred property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getTurnoverSuppliesServicesByWhichVATTaxationIsTransferred() {
        return turnoverSuppliesServicesByWhichVATTaxationIsTransferred;
    }

    /**
     * Sets the value of the turnoverSuppliesServicesByWhichVATTaxationIsTransferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setTurnoverSuppliesServicesByWhichVATTaxationIsTransferred(MonetaryNoDecimals10VItemType value) {
        this.turnoverSuppliesServicesByWhichVATTaxationIsTransferred = value;
    }

    /**
     * Gets the value of the valueAddedTaxOnInput property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getValueAddedTaxOnInput() {
        return valueAddedTaxOnInput;
    }

    /**
     * Sets the value of the valueAddedTaxOnInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setValueAddedTaxOnInput(MonetaryNoDecimals10VItemType value) {
        this.valueAddedTaxOnInput = value;
    }

    /**
     * Gets the value of the valueAddedTaxOnSuppliesFromCountriesOutsideTheEC property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public MonetaryNoDecimals9VItemType getValueAddedTaxOnSuppliesFromCountriesOutsideTheEC() {
        return valueAddedTaxOnSuppliesFromCountriesOutsideTheEC;
    }

    /**
     * Sets the value of the valueAddedTaxOnSuppliesFromCountriesOutsideTheEC property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public void setValueAddedTaxOnSuppliesFromCountriesOutsideTheEC(MonetaryNoDecimals9VItemType value) {
        this.valueAddedTaxOnSuppliesFromCountriesOutsideTheEC = value;
    }

    /**
     * Gets the value of the valueAddedTaxOnSuppliesFromCountriesWithinTheEC property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public MonetaryNoDecimals9VItemType getValueAddedTaxOnSuppliesFromCountriesWithinTheEC() {
        return valueAddedTaxOnSuppliesFromCountriesWithinTheEC;
    }

    /**
     * Sets the value of the valueAddedTaxOnSuppliesFromCountriesWithinTheEC property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public void setValueAddedTaxOnSuppliesFromCountriesWithinTheEC(MonetaryNoDecimals9VItemType value) {
        this.valueAddedTaxOnSuppliesFromCountriesWithinTheEC = value;
    }

    /**
     * Gets the value of the valueAddedTaxOwed property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getValueAddedTaxOwed() {
        return valueAddedTaxOwed;
    }

    /**
     * Sets the value of the valueAddedTaxOwed property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setValueAddedTaxOwed(MonetaryNoDecimals10VItemType value) {
        this.valueAddedTaxOwed = value;
    }

    /**
     * Gets the value of the valueAddedTaxOwedToBePaidBack property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public MonetaryNoDecimals9VItemType getValueAddedTaxOwedToBePaidBack() {
        return valueAddedTaxOwedToBePaidBack;
    }

    /**
     * Sets the value of the valueAddedTaxOwedToBePaidBack property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public void setValueAddedTaxOwedToBePaidBack(MonetaryNoDecimals9VItemType value) {
        this.valueAddedTaxOwedToBePaidBack = value;
    }

    /**
     * Gets the value of the valueAddedTaxPrivateUse property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public MonetaryNoDecimals9VItemType getValueAddedTaxPrivateUse() {
        return valueAddedTaxPrivateUse;
    }

    /**
     * Sets the value of the valueAddedTaxPrivateUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public void setValueAddedTaxPrivateUse(MonetaryNoDecimals9VItemType value) {
        this.valueAddedTaxPrivateUse = value;
    }

    /**
     * Gets the value of the valueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public MonetaryNoDecimals9VItemType getValueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred() {
        return valueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred;
    }

    /**
     * Sets the value of the valueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public void setValueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred(MonetaryNoDecimals9VItemType value) {
        this.valueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred = value;
    }

    /**
     * Gets the value of the valueAddedTaxSuppliesServicesGeneralTariff property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public MonetaryNoDecimals9VItemType getValueAddedTaxSuppliesServicesGeneralTariff() {
        return valueAddedTaxSuppliesServicesGeneralTariff;
    }

    /**
     * Sets the value of the valueAddedTaxSuppliesServicesGeneralTariff property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public void setValueAddedTaxSuppliesServicesGeneralTariff(MonetaryNoDecimals9VItemType value) {
        this.valueAddedTaxSuppliesServicesGeneralTariff = value;
    }

    /**
     * Gets the value of the valueAddedTaxSuppliesServicesOtherRates property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public MonetaryNoDecimals9VItemType getValueAddedTaxSuppliesServicesOtherRates() {
        return valueAddedTaxSuppliesServicesOtherRates;
    }

    /**
     * Sets the value of the valueAddedTaxSuppliesServicesOtherRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public void setValueAddedTaxSuppliesServicesOtherRates(MonetaryNoDecimals9VItemType value) {
        this.valueAddedTaxSuppliesServicesOtherRates = value;
    }

    /**
     * Gets the value of the valueAddedTaxSuppliesServicesReducedTariff property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public MonetaryNoDecimals9VItemType getValueAddedTaxSuppliesServicesReducedTariff() {
        return valueAddedTaxSuppliesServicesReducedTariff;
    }

    /**
     * Sets the value of the valueAddedTaxSuppliesServicesReducedTariff property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals9VItemType }
     *     
     */
    public void setValueAddedTaxSuppliesServicesReducedTariff(MonetaryNoDecimals9VItemType value) {
        this.valueAddedTaxSuppliesServicesReducedTariff = value;
    }

    /**
     * Gets the value of the versionApplication property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring2FItemType }
     *     
     */
    public Anstring2FItemType getVersionApplication() {
        return versionApplication;
    }

    /**
     * Sets the value of the versionApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring2FItemType }
     *     
     */
    public void setVersionApplication(Anstring2FItemType value) {
        this.versionApplication = value;
    }

}
