//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.16 at 09:30:36 PM CEST 
//


package nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_omzetbelasting;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_codes.ApplicationIdItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_codes.ContactItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_codes.IsoCountrycodeECMemberStatesItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_codes.VatRateTypeItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_types.Anstring200VItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_types.Monetary102ItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_types.MonetaryNoDecimals10VItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_types.MonetaryNoDecimals4VItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_types.MonetaryNoDecimals9VItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_types.MonetaryNoDecimalsNoZero10VItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_types.Pure52ItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_types.VatIdentificationNumberItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_types.VatIdentificationNumberNLItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_types.VatNumberItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_types.VatReturnNumberItemType;
import nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_types.VoesNumberItemType;
import org.xbrl._2003.instance.BooleanItemType;
import org.xbrl._2003.instance.DateItemType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_omzetbelasting package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SuppliesServicesNotTaxed_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "SuppliesServicesNotTaxed");
    private final static QName _ValueAddedTaxSuppliesServicesGeneralTariff_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ValueAddedTaxSuppliesServicesGeneralTariff");
    private final static QName _TaxedTurnoverPrivateUse_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "TaxedTurnoverPrivateUse");
    private final static QName _VATReturnReferenceNumber_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "VATReturnReferenceNumber");
    private final static QName _MSIDVATNumber_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "MSIDVATNumber");
    private final static QName _ValueAddedTaxOwed_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ValueAddedTaxOwed");
    private final static QName _GrandTotalMSID_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "GrandTotalMSID");
    private final static QName _VATNumber_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "VATNumber");
    private final static QName _ValueAddedTaxSuppliesServicesReducedTariff_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ValueAddedTaxSuppliesServicesReducedTariff");
    private final static QName _VATReturnDeviatingPeriodStartDate_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "VATReturnDeviatingPeriodStartDate");
    private final static QName _ValueAddedTaxSuppliesServicesOtherRates_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ValueAddedTaxSuppliesServicesOtherRates");
    private final static QName _TaxedTurnoverSuppliesServicesGeneralTariff_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "TaxedTurnoverSuppliesServicesGeneralTariff");
    private final static QName _MSIDVOESNumber_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "MSIDVOESNumber");
    private final static QName _TurnoverFromTaxedSuppliesFromCountriesOutsideTheEC_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "TurnoverFromTaxedSuppliesFromCountriesOutsideTheEC");
    private final static QName _ValueAddedTaxAmountTotalNew_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ValueAddedTaxAmountTotalNew");
    private final static QName _ValueAddedTaxPrivateUse_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ValueAddedTaxPrivateUse");
    private final static QName _GrandTotalMSEST_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "GrandTotalMSEST");
    private final static QName _InstallationDistanceSalesWithinTheEC_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "InstallationDistanceSalesWithinTheEC");
    private final static QName _ValueAddedTaxOnSuppliesFromCountriesOutsideTheEC_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ValueAddedTaxOnSuppliesFromCountriesOutsideTheEC");
    private final static QName _ServicesAmount_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ServicesAmount");
    private final static QName _ContactType_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ContactType");
    private final static QName _VATIdentificationNumberNLFiscalEntityDivision_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "VATIdentificationNumberNLFiscalEntityDivision");
    private final static QName _ApplicationId_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ApplicationId");
    private final static QName _MSIDCountryCode_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "MSIDCountryCode");
    private final static QName _ValueAddedTaxAmountTotalOld_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ValueAddedTaxAmountTotalOld");
    private final static QName _VATReturnNil_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "VATReturnNil");
    private final static QName _TurnoverSuppliesServicesByWhichVATTaxationIsTransferred_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "TurnoverSuppliesServicesByWhichVATTaxationIsTransferred");
    private final static QName _VATReturnDeviatingPeriodEndDate_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "VATReturnDeviatingPeriodEndDate");
    private final static QName _VATRateType_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "VATRateType");
    private final static QName _ValueAddedTaxOwedToBePaidBack_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ValueAddedTaxOwedToBePaidBack");
    private final static QName _SuppliesAmount_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "SuppliesAmount");
    private final static QName _VATRate_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "VATRate");
    private final static QName _VATIdentificationNumberNational_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "VATIdentificationNumberNational");
    private final static QName _ValueAddedTaxOnSuppliesFromCountriesWithinTheEC_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ValueAddedTaxOnSuppliesFromCountriesWithinTheEC");
    private final static QName _VATNumberCountryCode_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "VATNumberCountryCode");
    private final static QName _VATAmount_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "VATAmount");
    private final static QName _ValueAddedTaxToBePaidAdditionalToBePaidBack_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ValueAddedTaxToBePaidAdditionalToBePaidBack");
    private final static QName _TaxedTurnoverSuppliesServicesOtherRates_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "TaxedTurnoverSuppliesServicesOtherRates");
    private final static QName _TurnoverFromTaxedSuppliesFromCountriesWithinTheEC_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "TurnoverFromTaxedSuppliesFromCountriesWithinTheEC");
    private final static QName _SuppliesToCountriesWithinTheEC_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "SuppliesToCountriesWithinTheEC");
    private final static QName _CorrectionsServicesAmount_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "CorrectionsServicesAmount");
    private final static QName _ValueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ValueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred");
    private final static QName _CountryCodeISOEC_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "CountryCodeISO-EC");
    private final static QName _GrandTotal_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "GrandTotal");
    private final static QName _SmallEntrepreneurProvisionReduction_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "SmallEntrepreneurProvisionReduction");
    private final static QName _SuppliesToCountriesOutsideTheEC_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "SuppliesToCountriesOutsideTheEC");
    private final static QName _TaxedTurnoverSuppliesServicesReducedTariff_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "TaxedTurnoverSuppliesServicesReducedTariff");
    private final static QName _TaxableAmount_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "TaxableAmount");
    private final static QName _ValueAddedTaxOnInput_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "ValueAddedTaxOnInput");
    private final static QName _MSCONCountryCode_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "MSCONCountryCode");
    private final static QName _CorrectionsSuppliesAmount_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "CorrectionsSuppliesAmount");
    private final static QName _CompanyName_QNAME = new QName("http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", "CompanyName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.nltaxonomie.nt11.bd._20161207.dictionary.bd_omzetbelasting
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "SuppliesServicesNotTaxed", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createSuppliesServicesNotTaxed(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_SuppliesServicesNotTaxed_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals9VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ValueAddedTaxSuppliesServicesGeneralTariff", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals9VItemType> createValueAddedTaxSuppliesServicesGeneralTariff(MonetaryNoDecimals9VItemType value) {
        return new JAXBElement<MonetaryNoDecimals9VItemType>(_ValueAddedTaxSuppliesServicesGeneralTariff_QNAME, MonetaryNoDecimals9VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "TaxedTurnoverPrivateUse", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createTaxedTurnoverPrivateUse(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_TaxedTurnoverPrivateUse_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VatReturnNumberItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "VATReturnReferenceNumber", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<VatReturnNumberItemType> createVATReturnReferenceNumber(VatReturnNumberItemType value) {
        return new JAXBElement<VatReturnNumberItemType>(_VATReturnReferenceNumber_QNAME, VatReturnNumberItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VatNumberItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "MSIDVATNumber", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<VatNumberItemType> createMSIDVATNumber(VatNumberItemType value) {
        return new JAXBElement<VatNumberItemType>(_MSIDVATNumber_QNAME, VatNumberItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ValueAddedTaxOwed", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createValueAddedTaxOwed(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_ValueAddedTaxOwed_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Monetary102ItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "GrandTotalMSID", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<Monetary102ItemType> createGrandTotalMSID(Monetary102ItemType value) {
        return new JAXBElement<Monetary102ItemType>(_GrandTotalMSID_QNAME, Monetary102ItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VatNumberItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "VATNumber", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<VatNumberItemType> createVATNumber(VatNumberItemType value) {
        return new JAXBElement<VatNumberItemType>(_VATNumber_QNAME, VatNumberItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals9VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ValueAddedTaxSuppliesServicesReducedTariff", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals9VItemType> createValueAddedTaxSuppliesServicesReducedTariff(MonetaryNoDecimals9VItemType value) {
        return new JAXBElement<MonetaryNoDecimals9VItemType>(_ValueAddedTaxSuppliesServicesReducedTariff_QNAME, MonetaryNoDecimals9VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "VATReturnDeviatingPeriodStartDate", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<DateItemType> createVATReturnDeviatingPeriodStartDate(DateItemType value) {
        return new JAXBElement<DateItemType>(_VATReturnDeviatingPeriodStartDate_QNAME, DateItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals9VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ValueAddedTaxSuppliesServicesOtherRates", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals9VItemType> createValueAddedTaxSuppliesServicesOtherRates(MonetaryNoDecimals9VItemType value) {
        return new JAXBElement<MonetaryNoDecimals9VItemType>(_ValueAddedTaxSuppliesServicesOtherRates_QNAME, MonetaryNoDecimals9VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "TaxedTurnoverSuppliesServicesGeneralTariff", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createTaxedTurnoverSuppliesServicesGeneralTariff(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_TaxedTurnoverSuppliesServicesGeneralTariff_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VoesNumberItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "MSIDVOESNumber", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<VoesNumberItemType> createMSIDVOESNumber(VoesNumberItemType value) {
        return new JAXBElement<VoesNumberItemType>(_MSIDVOESNumber_QNAME, VoesNumberItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "TurnoverFromTaxedSuppliesFromCountriesOutsideTheEC", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createTurnoverFromTaxedSuppliesFromCountriesOutsideTheEC(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_TurnoverFromTaxedSuppliesFromCountriesOutsideTheEC_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ValueAddedTaxAmountTotalNew", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createValueAddedTaxAmountTotalNew(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_ValueAddedTaxAmountTotalNew_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals9VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ValueAddedTaxPrivateUse", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals9VItemType> createValueAddedTaxPrivateUse(MonetaryNoDecimals9VItemType value) {
        return new JAXBElement<MonetaryNoDecimals9VItemType>(_ValueAddedTaxPrivateUse_QNAME, MonetaryNoDecimals9VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Monetary102ItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "GrandTotalMSEST", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<Monetary102ItemType> createGrandTotalMSEST(Monetary102ItemType value) {
        return new JAXBElement<Monetary102ItemType>(_GrandTotalMSEST_QNAME, Monetary102ItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "InstallationDistanceSalesWithinTheEC", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createInstallationDistanceSalesWithinTheEC(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_InstallationDistanceSalesWithinTheEC_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals9VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ValueAddedTaxOnSuppliesFromCountriesOutsideTheEC", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals9VItemType> createValueAddedTaxOnSuppliesFromCountriesOutsideTheEC(MonetaryNoDecimals9VItemType value) {
        return new JAXBElement<MonetaryNoDecimals9VItemType>(_ValueAddedTaxOnSuppliesFromCountriesOutsideTheEC_QNAME, MonetaryNoDecimals9VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimalsNoZero10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ServicesAmount", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimalsNoZero10VItemType> createServicesAmount(MonetaryNoDecimalsNoZero10VItemType value) {
        return new JAXBElement<MonetaryNoDecimalsNoZero10VItemType>(_ServicesAmount_QNAME, MonetaryNoDecimalsNoZero10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ContactType", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<ContactItemType> createContactType(ContactItemType value) {
        return new JAXBElement<ContactItemType>(_ContactType_QNAME, ContactItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VatIdentificationNumberNLItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "VATIdentificationNumberNLFiscalEntityDivision", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<VatIdentificationNumberNLItemType> createVATIdentificationNumberNLFiscalEntityDivision(VatIdentificationNumberNLItemType value) {
        return new JAXBElement<VatIdentificationNumberNLItemType>(_VATIdentificationNumberNLFiscalEntityDivision_QNAME, VatIdentificationNumberNLItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationIdItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ApplicationId", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<ApplicationIdItemType> createApplicationId(ApplicationIdItemType value) {
        return new JAXBElement<ApplicationIdItemType>(_ApplicationId_QNAME, ApplicationIdItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsoCountrycodeECMemberStatesItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "MSIDCountryCode", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<IsoCountrycodeECMemberStatesItemType> createMSIDCountryCode(IsoCountrycodeECMemberStatesItemType value) {
        return new JAXBElement<IsoCountrycodeECMemberStatesItemType>(_MSIDCountryCode_QNAME, IsoCountrycodeECMemberStatesItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ValueAddedTaxAmountTotalOld", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createValueAddedTaxAmountTotalOld(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_ValueAddedTaxAmountTotalOld_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BooleanItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "VATReturnNil", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<BooleanItemType> createVATReturnNil(BooleanItemType value) {
        return new JAXBElement<BooleanItemType>(_VATReturnNil_QNAME, BooleanItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "TurnoverSuppliesServicesByWhichVATTaxationIsTransferred", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createTurnoverSuppliesServicesByWhichVATTaxationIsTransferred(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_TurnoverSuppliesServicesByWhichVATTaxationIsTransferred_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "VATReturnDeviatingPeriodEndDate", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<DateItemType> createVATReturnDeviatingPeriodEndDate(DateItemType value) {
        return new JAXBElement<DateItemType>(_VATReturnDeviatingPeriodEndDate_QNAME, DateItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VatRateTypeItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "VATRateType", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<VatRateTypeItemType> createVATRateType(VatRateTypeItemType value) {
        return new JAXBElement<VatRateTypeItemType>(_VATRateType_QNAME, VatRateTypeItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals9VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ValueAddedTaxOwedToBePaidBack", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals9VItemType> createValueAddedTaxOwedToBePaidBack(MonetaryNoDecimals9VItemType value) {
        return new JAXBElement<MonetaryNoDecimals9VItemType>(_ValueAddedTaxOwedToBePaidBack_QNAME, MonetaryNoDecimals9VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimalsNoZero10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "SuppliesAmount", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimalsNoZero10VItemType> createSuppliesAmount(MonetaryNoDecimalsNoZero10VItemType value) {
        return new JAXBElement<MonetaryNoDecimalsNoZero10VItemType>(_SuppliesAmount_QNAME, MonetaryNoDecimalsNoZero10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pure52ItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "VATRate", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<Pure52ItemType> createVATRate(Pure52ItemType value) {
        return new JAXBElement<Pure52ItemType>(_VATRate_QNAME, Pure52ItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VatIdentificationNumberItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "VATIdentificationNumberNational", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<VatIdentificationNumberItemType> createVATIdentificationNumberNational(VatIdentificationNumberItemType value) {
        return new JAXBElement<VatIdentificationNumberItemType>(_VATIdentificationNumberNational_QNAME, VatIdentificationNumberItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals9VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ValueAddedTaxOnSuppliesFromCountriesWithinTheEC", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals9VItemType> createValueAddedTaxOnSuppliesFromCountriesWithinTheEC(MonetaryNoDecimals9VItemType value) {
        return new JAXBElement<MonetaryNoDecimals9VItemType>(_ValueAddedTaxOnSuppliesFromCountriesWithinTheEC_QNAME, MonetaryNoDecimals9VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsoCountrycodeECMemberStatesItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "VATNumberCountryCode", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<IsoCountrycodeECMemberStatesItemType> createVATNumberCountryCode(IsoCountrycodeECMemberStatesItemType value) {
        return new JAXBElement<IsoCountrycodeECMemberStatesItemType>(_VATNumberCountryCode_QNAME, IsoCountrycodeECMemberStatesItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Monetary102ItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "VATAmount", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<Monetary102ItemType> createVATAmount(Monetary102ItemType value) {
        return new JAXBElement<Monetary102ItemType>(_VATAmount_QNAME, Monetary102ItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals9VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ValueAddedTaxToBePaidAdditionalToBePaidBack", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals9VItemType> createValueAddedTaxToBePaidAdditionalToBePaidBack(MonetaryNoDecimals9VItemType value) {
        return new JAXBElement<MonetaryNoDecimals9VItemType>(_ValueAddedTaxToBePaidAdditionalToBePaidBack_QNAME, MonetaryNoDecimals9VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "TaxedTurnoverSuppliesServicesOtherRates", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createTaxedTurnoverSuppliesServicesOtherRates(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_TaxedTurnoverSuppliesServicesOtherRates_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "TurnoverFromTaxedSuppliesFromCountriesWithinTheEC", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createTurnoverFromTaxedSuppliesFromCountriesWithinTheEC(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_TurnoverFromTaxedSuppliesFromCountriesWithinTheEC_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "SuppliesToCountriesWithinTheEC", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createSuppliesToCountriesWithinTheEC(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_SuppliesToCountriesWithinTheEC_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimalsNoZero10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "CorrectionsServicesAmount", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimalsNoZero10VItemType> createCorrectionsServicesAmount(MonetaryNoDecimalsNoZero10VItemType value) {
        return new JAXBElement<MonetaryNoDecimalsNoZero10VItemType>(_CorrectionsServicesAmount_QNAME, MonetaryNoDecimalsNoZero10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals9VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ValueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals9VItemType> createValueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred(MonetaryNoDecimals9VItemType value) {
        return new JAXBElement<MonetaryNoDecimals9VItemType>(_ValueAddedTaxSuppliesServicesByWhichVATTaxationIsTransferred_QNAME, MonetaryNoDecimals9VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsoCountrycodeECMemberStatesItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "CountryCodeISO-EC", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<IsoCountrycodeECMemberStatesItemType> createCountryCodeISOEC(IsoCountrycodeECMemberStatesItemType value) {
        return new JAXBElement<IsoCountrycodeECMemberStatesItemType>(_CountryCodeISOEC_QNAME, IsoCountrycodeECMemberStatesItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Monetary102ItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "GrandTotal", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<Monetary102ItemType> createGrandTotal(Monetary102ItemType value) {
        return new JAXBElement<Monetary102ItemType>(_GrandTotal_QNAME, Monetary102ItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals4VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "SmallEntrepreneurProvisionReduction", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals4VItemType> createSmallEntrepreneurProvisionReduction(MonetaryNoDecimals4VItemType value) {
        return new JAXBElement<MonetaryNoDecimals4VItemType>(_SmallEntrepreneurProvisionReduction_QNAME, MonetaryNoDecimals4VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "SuppliesToCountriesOutsideTheEC", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createSuppliesToCountriesOutsideTheEC(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_SuppliesToCountriesOutsideTheEC_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "TaxedTurnoverSuppliesServicesReducedTariff", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createTaxedTurnoverSuppliesServicesReducedTariff(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_TaxedTurnoverSuppliesServicesReducedTariff_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Monetary102ItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "TaxableAmount", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<Monetary102ItemType> createTaxableAmount(Monetary102ItemType value) {
        return new JAXBElement<Monetary102ItemType>(_TaxableAmount_QNAME, Monetary102ItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimals10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "ValueAddedTaxOnInput", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimals10VItemType> createValueAddedTaxOnInput(MonetaryNoDecimals10VItemType value) {
        return new JAXBElement<MonetaryNoDecimals10VItemType>(_ValueAddedTaxOnInput_QNAME, MonetaryNoDecimals10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsoCountrycodeECMemberStatesItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "MSCONCountryCode", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<IsoCountrycodeECMemberStatesItemType> createMSCONCountryCode(IsoCountrycodeECMemberStatesItemType value) {
        return new JAXBElement<IsoCountrycodeECMemberStatesItemType>(_MSCONCountryCode_QNAME, IsoCountrycodeECMemberStatesItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonetaryNoDecimalsNoZero10VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "CorrectionsSuppliesAmount", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<MonetaryNoDecimalsNoZero10VItemType> createCorrectionsSuppliesAmount(MonetaryNoDecimalsNoZero10VItemType value) {
        return new JAXBElement<MonetaryNoDecimalsNoZero10VItemType>(_CorrectionsSuppliesAmount_QNAME, MonetaryNoDecimalsNoZero10VItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Anstring200VItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nltaxonomie.nl/nt11/bd/20161207/dictionary/bd-omzetbelasting", name = "CompanyName", substitutionHeadNamespace = "http://www.xbrl.org/2003/instance", substitutionHeadName = "item")
    public JAXBElement<Anstring200VItemType> createCompanyName(Anstring200VItemType value) {
        return new JAXBElement<Anstring200VItemType>(_CompanyName_QNAME, Anstring200VItemType.class, null, value);
    }

}
