//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.25 at 08:13:42 PM CEST 
//


package nl.nltaxonomie._9_0.domein.bd.tuples.bd_burg_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie._9_0.basis.bd.types.bd_types.Anstring10VItemType;
import nl.nltaxonomie._9_0.basis.bd.types.bd_types.Anstring200VItemType;
import nl.nltaxonomie._9_0.basis.bd.types.bd_types.Anstring40VItemType;
import nl.nltaxonomie._9_0.basis.bd.types.bd_types.MonetaryNoDecimals10VItemType;
import nl.nltaxonomie._9_0.basis.bd.types.bd_types.Test11ItemType;
import org.xbrl._2003.instance.BooleanItemType;
import org.xbrl._2003.instance.DateItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldAgreementStartDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldAmountPayedFor" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldDescription" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldPayedFor" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldReceiverBuyerDateOfBirth" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldReceiverBuyerIdentificationNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldReceiverBuyerInitials" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldReceiverBuyerPrefix" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldReceiverBuyerSurname" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldReceiverRevenueDateOfBrith" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldReceiverRevenueIdentificationNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldReceiverRevenueInitials" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldReceiverRevenuePrefix" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldReceiverRevenueSurname" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldRevenueReceivedByOtherPersonInstitution" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}CapitalComponentsDonatedSoldValue" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "capitalComponentsDonatedSoldAgreementStartDate",
    "capitalComponentsDonatedSoldAmountPayedFor",
    "capitalComponentsDonatedSoldDescription",
    "capitalComponentsDonatedSoldPayedFor",
    "capitalComponentsDonatedSoldReceiverBuyerDateOfBirth",
    "capitalComponentsDonatedSoldReceiverBuyerIdentificationNumber",
    "capitalComponentsDonatedSoldReceiverBuyerInitials",
    "capitalComponentsDonatedSoldReceiverBuyerPrefix",
    "capitalComponentsDonatedSoldReceiverBuyerSurname",
    "capitalComponentsDonatedSoldReceiverRevenueDateOfBrith",
    "capitalComponentsDonatedSoldReceiverRevenueIdentificationNumber",
    "capitalComponentsDonatedSoldReceiverRevenueInitials",
    "capitalComponentsDonatedSoldReceiverRevenuePrefix",
    "capitalComponentsDonatedSoldReceiverRevenueSurname",
    "capitalComponentsDonatedSoldRevenueReceivedByOtherPersonInstitution",
    "capitalComponentsDonatedSoldValue"
})
public class CapitalComponentsSpecification
    extends Placeholder
{

    @XmlElement(name = "CapitalComponentsDonatedSoldAgreementStartDate", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected DateItemType capitalComponentsDonatedSoldAgreementStartDate;
    @XmlElement(name = "CapitalComponentsDonatedSoldAmountPayedFor", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected MonetaryNoDecimals10VItemType capitalComponentsDonatedSoldAmountPayedFor;
    @XmlElement(name = "CapitalComponentsDonatedSoldDescription", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected Anstring40VItemType capitalComponentsDonatedSoldDescription;
    @XmlElement(name = "CapitalComponentsDonatedSoldPayedFor", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected BooleanItemType capitalComponentsDonatedSoldPayedFor;
    @XmlElement(name = "CapitalComponentsDonatedSoldReceiverBuyerDateOfBirth", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected DateItemType capitalComponentsDonatedSoldReceiverBuyerDateOfBirth;
    @XmlElement(name = "CapitalComponentsDonatedSoldReceiverBuyerIdentificationNumber", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected Test11ItemType capitalComponentsDonatedSoldReceiverBuyerIdentificationNumber;
    @XmlElement(name = "CapitalComponentsDonatedSoldReceiverBuyerInitials", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected Anstring10VItemType capitalComponentsDonatedSoldReceiverBuyerInitials;
    @XmlElement(name = "CapitalComponentsDonatedSoldReceiverBuyerPrefix", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected Anstring10VItemType capitalComponentsDonatedSoldReceiverBuyerPrefix;
    @XmlElement(name = "CapitalComponentsDonatedSoldReceiverBuyerSurname", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected Anstring200VItemType capitalComponentsDonatedSoldReceiverBuyerSurname;
    @XmlElement(name = "CapitalComponentsDonatedSoldReceiverRevenueDateOfBrith", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected DateItemType capitalComponentsDonatedSoldReceiverRevenueDateOfBrith;
    @XmlElement(name = "CapitalComponentsDonatedSoldReceiverRevenueIdentificationNumber", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected Test11ItemType capitalComponentsDonatedSoldReceiverRevenueIdentificationNumber;
    @XmlElement(name = "CapitalComponentsDonatedSoldReceiverRevenueInitials", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected Anstring10VItemType capitalComponentsDonatedSoldReceiverRevenueInitials;
    @XmlElement(name = "CapitalComponentsDonatedSoldReceiverRevenuePrefix", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected Anstring10VItemType capitalComponentsDonatedSoldReceiverRevenuePrefix;
    @XmlElement(name = "CapitalComponentsDonatedSoldReceiverRevenueSurname", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected Anstring200VItemType capitalComponentsDonatedSoldReceiverRevenueSurname;
    @XmlElement(name = "CapitalComponentsDonatedSoldRevenueReceivedByOtherPersonInstitution", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected BooleanItemType capitalComponentsDonatedSoldRevenueReceivedByOtherPersonInstitution;
    @XmlElement(name = "CapitalComponentsDonatedSoldValue", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected MonetaryNoDecimals10VItemType capitalComponentsDonatedSoldValue;

    /**
     * Gets the value of the capitalComponentsDonatedSoldAgreementStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateItemType }
     *     
     */
    public DateItemType getCapitalComponentsDonatedSoldAgreementStartDate() {
        return capitalComponentsDonatedSoldAgreementStartDate;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldAgreementStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldAgreementStartDate(DateItemType value) {
        this.capitalComponentsDonatedSoldAgreementStartDate = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldAmountPayedFor property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getCapitalComponentsDonatedSoldAmountPayedFor() {
        return capitalComponentsDonatedSoldAmountPayedFor;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldAmountPayedFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldAmountPayedFor(MonetaryNoDecimals10VItemType value) {
        this.capitalComponentsDonatedSoldAmountPayedFor = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldDescription property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring40VItemType }
     *     
     */
    public Anstring40VItemType getCapitalComponentsDonatedSoldDescription() {
        return capitalComponentsDonatedSoldDescription;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring40VItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldDescription(Anstring40VItemType value) {
        this.capitalComponentsDonatedSoldDescription = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldPayedFor property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getCapitalComponentsDonatedSoldPayedFor() {
        return capitalComponentsDonatedSoldPayedFor;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldPayedFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldPayedFor(BooleanItemType value) {
        this.capitalComponentsDonatedSoldPayedFor = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldReceiverBuyerDateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link DateItemType }
     *     
     */
    public DateItemType getCapitalComponentsDonatedSoldReceiverBuyerDateOfBirth() {
        return capitalComponentsDonatedSoldReceiverBuyerDateOfBirth;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldReceiverBuyerDateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldReceiverBuyerDateOfBirth(DateItemType value) {
        this.capitalComponentsDonatedSoldReceiverBuyerDateOfBirth = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldReceiverBuyerIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Test11ItemType }
     *     
     */
    public Test11ItemType getCapitalComponentsDonatedSoldReceiverBuyerIdentificationNumber() {
        return capitalComponentsDonatedSoldReceiverBuyerIdentificationNumber;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldReceiverBuyerIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Test11ItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldReceiverBuyerIdentificationNumber(Test11ItemType value) {
        this.capitalComponentsDonatedSoldReceiverBuyerIdentificationNumber = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldReceiverBuyerInitials property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring10VItemType }
     *     
     */
    public Anstring10VItemType getCapitalComponentsDonatedSoldReceiverBuyerInitials() {
        return capitalComponentsDonatedSoldReceiverBuyerInitials;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldReceiverBuyerInitials property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring10VItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldReceiverBuyerInitials(Anstring10VItemType value) {
        this.capitalComponentsDonatedSoldReceiverBuyerInitials = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldReceiverBuyerPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring10VItemType }
     *     
     */
    public Anstring10VItemType getCapitalComponentsDonatedSoldReceiverBuyerPrefix() {
        return capitalComponentsDonatedSoldReceiverBuyerPrefix;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldReceiverBuyerPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring10VItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldReceiverBuyerPrefix(Anstring10VItemType value) {
        this.capitalComponentsDonatedSoldReceiverBuyerPrefix = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldReceiverBuyerSurname property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring200VItemType }
     *     
     */
    public Anstring200VItemType getCapitalComponentsDonatedSoldReceiverBuyerSurname() {
        return capitalComponentsDonatedSoldReceiverBuyerSurname;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldReceiverBuyerSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring200VItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldReceiverBuyerSurname(Anstring200VItemType value) {
        this.capitalComponentsDonatedSoldReceiverBuyerSurname = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldReceiverRevenueDateOfBrith property.
     * 
     * @return
     *     possible object is
     *     {@link DateItemType }
     *     
     */
    public DateItemType getCapitalComponentsDonatedSoldReceiverRevenueDateOfBrith() {
        return capitalComponentsDonatedSoldReceiverRevenueDateOfBrith;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldReceiverRevenueDateOfBrith property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldReceiverRevenueDateOfBrith(DateItemType value) {
        this.capitalComponentsDonatedSoldReceiverRevenueDateOfBrith = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldReceiverRevenueIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Test11ItemType }
     *     
     */
    public Test11ItemType getCapitalComponentsDonatedSoldReceiverRevenueIdentificationNumber() {
        return capitalComponentsDonatedSoldReceiverRevenueIdentificationNumber;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldReceiverRevenueIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Test11ItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldReceiverRevenueIdentificationNumber(Test11ItemType value) {
        this.capitalComponentsDonatedSoldReceiverRevenueIdentificationNumber = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldReceiverRevenueInitials property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring10VItemType }
     *     
     */
    public Anstring10VItemType getCapitalComponentsDonatedSoldReceiverRevenueInitials() {
        return capitalComponentsDonatedSoldReceiverRevenueInitials;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldReceiverRevenueInitials property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring10VItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldReceiverRevenueInitials(Anstring10VItemType value) {
        this.capitalComponentsDonatedSoldReceiverRevenueInitials = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldReceiverRevenuePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring10VItemType }
     *     
     */
    public Anstring10VItemType getCapitalComponentsDonatedSoldReceiverRevenuePrefix() {
        return capitalComponentsDonatedSoldReceiverRevenuePrefix;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldReceiverRevenuePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring10VItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldReceiverRevenuePrefix(Anstring10VItemType value) {
        this.capitalComponentsDonatedSoldReceiverRevenuePrefix = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldReceiverRevenueSurname property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring200VItemType }
     *     
     */
    public Anstring200VItemType getCapitalComponentsDonatedSoldReceiverRevenueSurname() {
        return capitalComponentsDonatedSoldReceiverRevenueSurname;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldReceiverRevenueSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring200VItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldReceiverRevenueSurname(Anstring200VItemType value) {
        this.capitalComponentsDonatedSoldReceiverRevenueSurname = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldRevenueReceivedByOtherPersonInstitution property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getCapitalComponentsDonatedSoldRevenueReceivedByOtherPersonInstitution() {
        return capitalComponentsDonatedSoldRevenueReceivedByOtherPersonInstitution;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldRevenueReceivedByOtherPersonInstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldRevenueReceivedByOtherPersonInstitution(BooleanItemType value) {
        this.capitalComponentsDonatedSoldRevenueReceivedByOtherPersonInstitution = value;
    }

    /**
     * Gets the value of the capitalComponentsDonatedSoldValue property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getCapitalComponentsDonatedSoldValue() {
        return capitalComponentsDonatedSoldValue;
    }

    /**
     * Sets the value of the capitalComponentsDonatedSoldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setCapitalComponentsDonatedSoldValue(MonetaryNoDecimals10VItemType value) {
        this.capitalComponentsDonatedSoldValue = value;
    }

}
