//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.25 at 08:13:42 PM CEST 
//


package nl.nltaxonomie._9_0.domein.bd.tuples.bd_burg_tuples;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie._9_0.basis.bd.types.bd_types.StudyYearItemType;
import nl.nltaxonomie._9_0.basis.sbr.types.nl_types.NonNegativeMonetaryNoDecimalsItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}LoanFinalStudyYearDataDeductableAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}LoanFinalStudyYearDataForfaitAmountTotal" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}LoanFinalStudyYearDataLoanFinalAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}LoanFinalStudyYearDataStudyYear" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/domein/bd/tuples/bd-burg-tuples}LoanFinalStudyYearPeriodSpecification" maxOccurs="99" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "loanFinalStudyYearDataDeductableAmount",
    "loanFinalStudyYearDataForfaitAmountTotal",
    "loanFinalStudyYearDataLoanFinalAmount",
    "loanFinalStudyYearDataStudyYear",
    "loanFinalStudyYearPeriodSpecification"
})
public class LoanFinalStudyYearDataSpecification
    extends Placeholder
{

    @XmlElement(name = "LoanFinalStudyYearDataDeductableAmount", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected NonNegativeMonetaryNoDecimalsItemType loanFinalStudyYearDataDeductableAmount;
    @XmlElement(name = "LoanFinalStudyYearDataForfaitAmountTotal", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected NonNegativeMonetaryNoDecimalsItemType loanFinalStudyYearDataForfaitAmountTotal;
    @XmlElement(name = "LoanFinalStudyYearDataLoanFinalAmount", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected NonNegativeMonetaryNoDecimalsItemType loanFinalStudyYearDataLoanFinalAmount;
    @XmlElement(name = "LoanFinalStudyYearDataStudyYear", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected StudyYearItemType loanFinalStudyYearDataStudyYear;
    @XmlElement(name = "LoanFinalStudyYearPeriodSpecification", namespace = "http://www.nltaxonomie.nl/9.0/domein/bd/tuples/bd-burg-tuples")
    protected List<LoanFinalStudyYearPeriodSpecification> loanFinalStudyYearPeriodSpecification;

    /**
     * Gets the value of the loanFinalStudyYearDataDeductableAmount property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getLoanFinalStudyYearDataDeductableAmount() {
        return loanFinalStudyYearDataDeductableAmount;
    }

    /**
     * Sets the value of the loanFinalStudyYearDataDeductableAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setLoanFinalStudyYearDataDeductableAmount(NonNegativeMonetaryNoDecimalsItemType value) {
        this.loanFinalStudyYearDataDeductableAmount = value;
    }

    /**
     * Gets the value of the loanFinalStudyYearDataForfaitAmountTotal property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getLoanFinalStudyYearDataForfaitAmountTotal() {
        return loanFinalStudyYearDataForfaitAmountTotal;
    }

    /**
     * Sets the value of the loanFinalStudyYearDataForfaitAmountTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setLoanFinalStudyYearDataForfaitAmountTotal(NonNegativeMonetaryNoDecimalsItemType value) {
        this.loanFinalStudyYearDataForfaitAmountTotal = value;
    }

    /**
     * Gets the value of the loanFinalStudyYearDataLoanFinalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getLoanFinalStudyYearDataLoanFinalAmount() {
        return loanFinalStudyYearDataLoanFinalAmount;
    }

    /**
     * Sets the value of the loanFinalStudyYearDataLoanFinalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setLoanFinalStudyYearDataLoanFinalAmount(NonNegativeMonetaryNoDecimalsItemType value) {
        this.loanFinalStudyYearDataLoanFinalAmount = value;
    }

    /**
     * Gets the value of the loanFinalStudyYearDataStudyYear property.
     * 
     * @return
     *     possible object is
     *     {@link StudyYearItemType }
     *     
     */
    public StudyYearItemType getLoanFinalStudyYearDataStudyYear() {
        return loanFinalStudyYearDataStudyYear;
    }

    /**
     * Sets the value of the loanFinalStudyYearDataStudyYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudyYearItemType }
     *     
     */
    public void setLoanFinalStudyYearDataStudyYear(StudyYearItemType value) {
        this.loanFinalStudyYearDataStudyYear = value;
    }

    /**
     * Gets the value of the loanFinalStudyYearPeriodSpecification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loanFinalStudyYearPeriodSpecification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoanFinalStudyYearPeriodSpecification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoanFinalStudyYearPeriodSpecification }
     * 
     * 
     */
    public List<LoanFinalStudyYearPeriodSpecification> getLoanFinalStudyYearPeriodSpecification() {
        if (loanFinalStudyYearPeriodSpecification == null) {
            loanFinalStudyYearPeriodSpecification = new ArrayList<LoanFinalStudyYearPeriodSpecification>();
        }
        return this.loanFinalStudyYearPeriodSpecification;
    }

}
