//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.25 at 08:13:42 PM CEST 
//


package nl.nltaxonomie._9_0.domein.bd.tuples.bd_burg_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie._9_0.basis.bd.types.bd_types.Anstring35VItemType;
import nl.nltaxonomie._9_0.basis.bd.types.bd_types.Anstring70VItemType;
import nl.nltaxonomie._9_0.basis.bd.types.bd_types.MonetaryNoDecimals10VItemType;
import nl.nltaxonomie._9_0.basis.bd.types.bd_types.Test11ItemType;
//import org.iso.iso3166.iso3166_countrycodes_2013_07_11.IsoCountryCodes3CharactersItemType;
import nl.nltaxonomie.iso.iso3166.IsoCountryCodes3CharactersItemType;
import org.xbrl._2003.instance.BooleanItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}TrustCapitalCountry" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}TrustCapitalIdentificationNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}TrustCapitalLegalForm" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}TrustCapitalLeviedTaxForeignCountryAtLeastTenPercentExists" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}TrustCapitalName"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers}TrustCapitalValue" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trustCapitalCountry",
    "trustCapitalIdentificationNumber",
    "trustCapitalLegalForm",
    "trustCapitalLeviedTaxForeignCountryAtLeastTenPercentExists",
    "trustCapitalName",
    "trustCapitalValue"
})
public class TrustCapitalSpecification
    extends Placeholder
{

    @XmlElement(name = "TrustCapitalCountry", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected IsoCountryCodes3CharactersItemType trustCapitalCountry;
    @XmlElement(name = "TrustCapitalIdentificationNumber", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected Test11ItemType trustCapitalIdentificationNumber;
    @XmlElement(name = "TrustCapitalLegalForm", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected Anstring35VItemType trustCapitalLegalForm;
    @XmlElement(name = "TrustCapitalLeviedTaxForeignCountryAtLeastTenPercentExists", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected BooleanItemType trustCapitalLeviedTaxForeignCountryAtLeastTenPercentExists;
    @XmlElement(name = "TrustCapitalName", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers", required = true)
    protected Anstring70VItemType trustCapitalName;
    @XmlElement(name = "TrustCapitalValue", namespace = "http://www.nltaxonomie.nl/9.0/basis/bd/items/bd-burgers")
    protected MonetaryNoDecimals10VItemType trustCapitalValue;

    /**
     * Gets the value of the trustCapitalCountry property.
     * 
     * @return
     *     possible object is
     *     {@link IsoCountryCodes3CharactersItemType }
     *     
     */
    public IsoCountryCodes3CharactersItemType getTrustCapitalCountry() {
        return trustCapitalCountry;
    }

    /**
     * Sets the value of the trustCapitalCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsoCountryCodes3CharactersItemType }
     *     
     */
    public void setTrustCapitalCountry(IsoCountryCodes3CharactersItemType value) {
        this.trustCapitalCountry = value;
    }

    /**
     * Gets the value of the trustCapitalIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Test11ItemType }
     *     
     */
    public Test11ItemType getTrustCapitalIdentificationNumber() {
        return trustCapitalIdentificationNumber;
    }

    /**
     * Sets the value of the trustCapitalIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Test11ItemType }
     *     
     */
    public void setTrustCapitalIdentificationNumber(Test11ItemType value) {
        this.trustCapitalIdentificationNumber = value;
    }

    /**
     * Gets the value of the trustCapitalLegalForm property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring35VItemType }
     *     
     */
    public Anstring35VItemType getTrustCapitalLegalForm() {
        return trustCapitalLegalForm;
    }

    /**
     * Sets the value of the trustCapitalLegalForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring35VItemType }
     *     
     */
    public void setTrustCapitalLegalForm(Anstring35VItemType value) {
        this.trustCapitalLegalForm = value;
    }

    /**
     * Gets the value of the trustCapitalLeviedTaxForeignCountryAtLeastTenPercentExists property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanItemType }
     *     
     */
    public BooleanItemType getTrustCapitalLeviedTaxForeignCountryAtLeastTenPercentExists() {
        return trustCapitalLeviedTaxForeignCountryAtLeastTenPercentExists;
    }

    /**
     * Sets the value of the trustCapitalLeviedTaxForeignCountryAtLeastTenPercentExists property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanItemType }
     *     
     */
    public void setTrustCapitalLeviedTaxForeignCountryAtLeastTenPercentExists(BooleanItemType value) {
        this.trustCapitalLeviedTaxForeignCountryAtLeastTenPercentExists = value;
    }

    /**
     * Gets the value of the trustCapitalName property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring70VItemType }
     *     
     */
    public Anstring70VItemType getTrustCapitalName() {
        return trustCapitalName;
    }

    /**
     * Sets the value of the trustCapitalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring70VItemType }
     *     
     */
    public void setTrustCapitalName(Anstring70VItemType value) {
        this.trustCapitalName = value;
    }

    /**
     * Gets the value of the trustCapitalValue property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public MonetaryNoDecimals10VItemType getTrustCapitalValue() {
        return trustCapitalValue;
    }

    /**
     * Sets the value of the trustCapitalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimals10VItemType }
     *     
     */
    public void setTrustCapitalValue(MonetaryNoDecimals10VItemType value) {
        this.trustCapitalValue = value;
    }

}
