//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.10 at 11:10:53 AM CEST 
//


package nl.nltaxonomie.nt13.bd._20181212.dictionary.bd_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie.nt13.bd._20181212.dictionary.bd_types.NonNegativeInteger6VItemType;
import nl.nltaxonomie.nt13.sbr._20180301.dictionary.nl_types.NonNegativeMonetaryNoDecimalsItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-tuples}AddressAbroadPresentation" minOccurs="0"/>
 *           &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-tuples}AddressPresentation" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-data}ListedBuildingDeductibleExpenses" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-data}ListedBuildingMaintenanceCostsAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-data}ListedBuildingNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-data}ListedBuildingSubsidy" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addressAbroadPresentation",
    "addressPresentation",
    "listedBuildingDeductibleExpenses",
    "listedBuildingMaintenanceCostsAmount",
    "listedBuildingNumber",
    "listedBuildingSubsidy"
})
public class ListedBuildingCostsSpecification
    extends Placeholder
{

    @XmlElement(name = "AddressAbroadPresentation", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-tuples")
    protected AddressAbroadPresentation addressAbroadPresentation;
    @XmlElement(name = "AddressPresentation", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-tuples")
    protected AddressPresentation addressPresentation;
    @XmlElement(name = "ListedBuildingDeductibleExpenses", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-data")
    protected NonNegativeMonetaryNoDecimalsItemType listedBuildingDeductibleExpenses;
    @XmlElement(name = "ListedBuildingMaintenanceCostsAmount", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-data")
    protected NonNegativeMonetaryNoDecimalsItemType listedBuildingMaintenanceCostsAmount;
    @XmlElement(name = "ListedBuildingNumber", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-data")
    protected NonNegativeInteger6VItemType listedBuildingNumber;
    @XmlElement(name = "ListedBuildingSubsidy", namespace = "http://www.nltaxonomie.nl/nt13/bd/20181212/dictionary/bd-data")
    protected NonNegativeMonetaryNoDecimalsItemType listedBuildingSubsidy;

    /**
     * Gets the value of the addressAbroadPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link AddressAbroadPresentation }
     *     
     */
    public AddressAbroadPresentation getAddressAbroadPresentation() {
        return addressAbroadPresentation;
    }

    /**
     * Sets the value of the addressAbroadPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressAbroadPresentation }
     *     
     */
    public void setAddressAbroadPresentation(AddressAbroadPresentation value) {
        this.addressAbroadPresentation = value;
    }

    /**
     * Gets the value of the addressPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link AddressPresentation }
     *     
     */
    public AddressPresentation getAddressPresentation() {
        return addressPresentation;
    }

    /**
     * Sets the value of the addressPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressPresentation }
     *     
     */
    public void setAddressPresentation(AddressPresentation value) {
        this.addressPresentation = value;
    }

    /**
     * Gets the value of the listedBuildingDeductibleExpenses property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getListedBuildingDeductibleExpenses() {
        return listedBuildingDeductibleExpenses;
    }

    /**
     * Sets the value of the listedBuildingDeductibleExpenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setListedBuildingDeductibleExpenses(NonNegativeMonetaryNoDecimalsItemType value) {
        this.listedBuildingDeductibleExpenses = value;
    }

    /**
     * Gets the value of the listedBuildingMaintenanceCostsAmount property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getListedBuildingMaintenanceCostsAmount() {
        return listedBuildingMaintenanceCostsAmount;
    }

    /**
     * Sets the value of the listedBuildingMaintenanceCostsAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setListedBuildingMaintenanceCostsAmount(NonNegativeMonetaryNoDecimalsItemType value) {
        this.listedBuildingMaintenanceCostsAmount = value;
    }

    /**
     * Gets the value of the listedBuildingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeInteger6VItemType }
     *     
     */
    public NonNegativeInteger6VItemType getListedBuildingNumber() {
        return listedBuildingNumber;
    }

    /**
     * Sets the value of the listedBuildingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeInteger6VItemType }
     *     
     */
    public void setListedBuildingNumber(NonNegativeInteger6VItemType value) {
        this.listedBuildingNumber = value;
    }

    /**
     * Gets the value of the listedBuildingSubsidy property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getListedBuildingSubsidy() {
        return listedBuildingSubsidy;
    }

    /**
     * Sets the value of the listedBuildingSubsidy property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setListedBuildingSubsidy(NonNegativeMonetaryNoDecimalsItemType value) {
        this.listedBuildingSubsidy = value;
    }

}
