//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 09:06:01 PM CET 
//


package nl.nltaxonomie._7_0_b_1.basis.kvk.types.kvk_codes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.nltaxonomie._7_0_b_1.basis.kvk.types.kvk_codes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.nltaxonomie._7_0_b_1.basis.kvk.types.kvk_codes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DirectorItemType }
     * 
     */
    public DirectorItemType createDirectorItemType() {
        return new DirectorItemType();
    }

    /**
     * Create an instance of {@link ConstructionContractsItemType }
     * 
     */
    public ConstructionContractsItemType createConstructionContractsItemType() {
        return new ConstructionContractsItemType();
    }

    /**
     * Create an instance of {@link LiabilitiesItemType }
     * 
     */
    public LiabilitiesItemType createLiabilitiesItemType() {
        return new LiabilitiesItemType();
    }

    /**
     * Create an instance of {@link LegalSizeCriteriaItemType }
     * 
     */
    public LegalSizeCriteriaItemType createLegalSizeCriteriaItemType() {
        return new LegalSizeCriteriaItemType();
    }

    /**
     * Create an instance of {@link EventItemType }
     * 
     */
    public EventItemType createEventItemType() {
        return new EventItemType();
    }

    /**
     * Create an instance of {@link RemunerationDirectorsItemType }
     * 
     */
    public RemunerationDirectorsItemType createRemunerationDirectorsItemType() {
        return new RemunerationDirectorsItemType();
    }

    /**
     * Create an instance of {@link LoanAdvanceGuaranteeItemType }
     * 
     */
    public LoanAdvanceGuaranteeItemType createLoanAdvanceGuaranteeItemType() {
        return new LoanAdvanceGuaranteeItemType();
    }

    /**
     * Create an instance of {@link TransactionItemType }
     * 
     */
    public TransactionItemType createTransactionItemType() {
        return new TransactionItemType();
    }

    /**
     * Create an instance of {@link FinancialInstrumentsItemType }
     * 
     */
    public FinancialInstrumentsItemType createFinancialInstrumentsItemType() {
        return new FinancialInstrumentsItemType();
    }

    /**
     * Create an instance of {@link ContactItemType }
     * 
     */
    public ContactItemType createContactItemType() {
        return new ContactItemType();
    }

}
