//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.09 at 10:28:44 PM CET 
//


package nl.nltaxonomie._8_0.domein.bd.tuples.bd_bedr_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie._8_0.basis.bd.types.bd_codes.FunctionalCurrencyFactorItemType;
import nl.nltaxonomie._8_0.basis.bd.types.bd_types.ExchangeRateItemType;
import nl.nltaxonomie._8_0.basis.sbr.types.nl_types.MonetaryNoDecimalsItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-bedrijven}ExchangeRateFinancialYearFunctionalCurrencySchemeAverage"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-bedrijven}FunctionalCurrencySchemeCurrencyFactor"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-bedrijven}TaxableAmountBaseForTaxCalculation"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "exchangeRateFinancialYearFunctionalCurrencySchemeAverage",
    "functionalCurrencySchemeCurrencyFactor",
    "taxableAmountBaseForTaxCalculation"
})
public class FunctionalCurrencyOrderSpecification
    extends Placeholder
{

    @XmlElement(name = "ExchangeRateFinancialYearFunctionalCurrencySchemeAverage", namespace = "http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-bedrijven", required = true)
    protected ExchangeRateItemType exchangeRateFinancialYearFunctionalCurrencySchemeAverage;
    @XmlElement(name = "FunctionalCurrencySchemeCurrencyFactor", namespace = "http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-bedrijven", required = true)
    protected FunctionalCurrencyFactorItemType functionalCurrencySchemeCurrencyFactor;
    @XmlElement(name = "TaxableAmountBaseForTaxCalculation", namespace = "http://www.nltaxonomie.nl/8.0/basis/bd/items/bd-bedrijven", required = true)
    protected MonetaryNoDecimalsItemType taxableAmountBaseForTaxCalculation;

    /**
     * Gets the value of the exchangeRateFinancialYearFunctionalCurrencySchemeAverage property.
     * 
     * @return
     *     possible object is
     *     {@link ExchangeRateItemType }
     *     
     */
    public ExchangeRateItemType getExchangeRateFinancialYearFunctionalCurrencySchemeAverage() {
        return exchangeRateFinancialYearFunctionalCurrencySchemeAverage;
    }

    /**
     * Sets the value of the exchangeRateFinancialYearFunctionalCurrencySchemeAverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExchangeRateItemType }
     *     
     */
    public void setExchangeRateFinancialYearFunctionalCurrencySchemeAverage(ExchangeRateItemType value) {
        this.exchangeRateFinancialYearFunctionalCurrencySchemeAverage = value;
    }

    /**
     * Gets the value of the functionalCurrencySchemeCurrencyFactor property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionalCurrencyFactorItemType }
     *     
     */
    public FunctionalCurrencyFactorItemType getFunctionalCurrencySchemeCurrencyFactor() {
        return functionalCurrencySchemeCurrencyFactor;
    }

    /**
     * Sets the value of the functionalCurrencySchemeCurrencyFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionalCurrencyFactorItemType }
     *     
     */
    public void setFunctionalCurrencySchemeCurrencyFactor(FunctionalCurrencyFactorItemType value) {
        this.functionalCurrencySchemeCurrencyFactor = value;
    }

    /**
     * Gets the value of the taxableAmountBaseForTaxCalculation property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getTaxableAmountBaseForTaxCalculation() {
        return taxableAmountBaseForTaxCalculation;
    }

    /**
     * Sets the value of the taxableAmountBaseForTaxCalculation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setTaxableAmountBaseForTaxCalculation(MonetaryNoDecimalsItemType value) {
        this.taxableAmountBaseForTaxCalculation = value;
    }

}
