//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 09:06:01 PM CET 
//


package nl.nltaxonomie._7_0_b_1.domein.bd.tuples.bd_bedr_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie._7_0.basis.sbr.types.nl_types.NonNegativeMonetaryNoDecimalsItemType;
import nl.nltaxonomie._7_0_b_1.basis.bd.types.bd_types.Anstring11FItemType;
import nl.nltaxonomie._7_0_b_1.basis.bd.types.bd_types.NonNegativeInteger7VItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-bedrijven}ExchangeRateFinancialYearFunctionalCurrencySchemeAverage"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-bedrijven}FunctionalCurrencySchemeCurrencyFactor"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-bedrijven}TaxableAmountBaseForTaxCalculation"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "exchangeRateFinancialYearFunctionalCurrencySchemeAverage",
    "functionalCurrencySchemeCurrencyFactor",
    "taxableAmountBaseForTaxCalculation"
})
public class FunctionalCurrencyOrderSpecification
    extends Placeholder
{

    @XmlElement(name = "ExchangeRateFinancialYearFunctionalCurrencySchemeAverage", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-bedrijven", required = true)
    protected Anstring11FItemType exchangeRateFinancialYearFunctionalCurrencySchemeAverage;
    @XmlElement(name = "FunctionalCurrencySchemeCurrencyFactor", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-bedrijven", required = true)
    protected NonNegativeInteger7VItemType functionalCurrencySchemeCurrencyFactor;
    @XmlElement(name = "TaxableAmountBaseForTaxCalculation", namespace = "http://www.nltaxonomie.nl/7.0.b.1/basis/bd/items/bd-bedrijven", required = true)
    protected NonNegativeMonetaryNoDecimalsItemType taxableAmountBaseForTaxCalculation;

    /**
     * Gets the value of the exchangeRateFinancialYearFunctionalCurrencySchemeAverage property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring11FItemType }
     *     
     */
    public Anstring11FItemType getExchangeRateFinancialYearFunctionalCurrencySchemeAverage() {
        return exchangeRateFinancialYearFunctionalCurrencySchemeAverage;
    }

    /**
     * Sets the value of the exchangeRateFinancialYearFunctionalCurrencySchemeAverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring11FItemType }
     *     
     */
    public void setExchangeRateFinancialYearFunctionalCurrencySchemeAverage(Anstring11FItemType value) {
        this.exchangeRateFinancialYearFunctionalCurrencySchemeAverage = value;
    }

    /**
     * Gets the value of the functionalCurrencySchemeCurrencyFactor property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeInteger7VItemType }
     *     
     */
    public NonNegativeInteger7VItemType getFunctionalCurrencySchemeCurrencyFactor() {
        return functionalCurrencySchemeCurrencyFactor;
    }

    /**
     * Sets the value of the functionalCurrencySchemeCurrencyFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeInteger7VItemType }
     *     
     */
    public void setFunctionalCurrencySchemeCurrencyFactor(NonNegativeInteger7VItemType value) {
        this.functionalCurrencySchemeCurrencyFactor = value;
    }

    /**
     * Gets the value of the taxableAmountBaseForTaxCalculation property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getTaxableAmountBaseForTaxCalculation() {
        return taxableAmountBaseForTaxCalculation;
    }

    /**
     * Sets the value of the taxableAmountBaseForTaxCalculation property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setTaxableAmountBaseForTaxCalculation(NonNegativeMonetaryNoDecimalsItemType value) {
        this.taxableAmountBaseForTaxCalculation = value;
    }

}
