//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.17 at 01:15:21 PM CEST 
//


package nl.nltaxonomie._8_0_a_2.domein.bd.tuples.bd_burg_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie._8_0.basis.sbr.types.nl_types.MonetaryNoDecimalsItemType;
import nl.nltaxonomie._8_0_a_2.basis.bd.types.bd_types.Anstring34VItemType;
import nl.nltaxonomie._8_0_a_2.basis.bd.types.bd_types.Anstring45VItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers}OwnHouseDebtBankAccountBalancePrefilled"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers}OwnHouseDebtBankAccountBalanceTaxpayerPrefilled" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers}OwnHouseDebtBankAccountBalanceTaxpayerSharePrefilled" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers}OwnHouseDebtBankAccountNumberPrefilled"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers}OwnHouseDebtBankProductDescriptionPrefilled"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ownHouseDebtBankAccountBalancePrefilled",
    "ownHouseDebtBankAccountBalanceTaxpayerPrefilled",
    "ownHouseDebtBankAccountBalanceTaxpayerSharePrefilled",
    "ownHouseDebtBankAccountNumberPrefilled",
    "ownHouseDebtBankProductDescriptionPrefilled"
})
public class OwnHouseDebtBankAccountPrefilledSpecification
    extends Placeholder
{

    @XmlElement(name = "OwnHouseDebtBankAccountBalancePrefilled", namespace = "http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers", required = true)
    protected MonetaryNoDecimalsItemType ownHouseDebtBankAccountBalancePrefilled;
    @XmlElement(name = "OwnHouseDebtBankAccountBalanceTaxpayerPrefilled", namespace = "http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers")
    protected MonetaryNoDecimalsItemType ownHouseDebtBankAccountBalanceTaxpayerPrefilled;
    @XmlElement(name = "OwnHouseDebtBankAccountBalanceTaxpayerSharePrefilled", namespace = "http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers")
    protected MonetaryNoDecimalsItemType ownHouseDebtBankAccountBalanceTaxpayerSharePrefilled;
    @XmlElement(name = "OwnHouseDebtBankAccountNumberPrefilled", namespace = "http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers", required = true)
    protected Anstring34VItemType ownHouseDebtBankAccountNumberPrefilled;
    @XmlElement(name = "OwnHouseDebtBankProductDescriptionPrefilled", namespace = "http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers", required = true)
    protected Anstring45VItemType ownHouseDebtBankProductDescriptionPrefilled;

    /**
     * Gets the value of the ownHouseDebtBankAccountBalancePrefilled property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getOwnHouseDebtBankAccountBalancePrefilled() {
        return ownHouseDebtBankAccountBalancePrefilled;
    }

    /**
     * Sets the value of the ownHouseDebtBankAccountBalancePrefilled property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setOwnHouseDebtBankAccountBalancePrefilled(MonetaryNoDecimalsItemType value) {
        this.ownHouseDebtBankAccountBalancePrefilled = value;
    }

    /**
     * Gets the value of the ownHouseDebtBankAccountBalanceTaxpayerPrefilled property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getOwnHouseDebtBankAccountBalanceTaxpayerPrefilled() {
        return ownHouseDebtBankAccountBalanceTaxpayerPrefilled;
    }

    /**
     * Sets the value of the ownHouseDebtBankAccountBalanceTaxpayerPrefilled property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setOwnHouseDebtBankAccountBalanceTaxpayerPrefilled(MonetaryNoDecimalsItemType value) {
        this.ownHouseDebtBankAccountBalanceTaxpayerPrefilled = value;
    }

    /**
     * Gets the value of the ownHouseDebtBankAccountBalanceTaxpayerSharePrefilled property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public MonetaryNoDecimalsItemType getOwnHouseDebtBankAccountBalanceTaxpayerSharePrefilled() {
        return ownHouseDebtBankAccountBalanceTaxpayerSharePrefilled;
    }

    /**
     * Sets the value of the ownHouseDebtBankAccountBalanceTaxpayerSharePrefilled property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryNoDecimalsItemType }
     *     
     */
    public void setOwnHouseDebtBankAccountBalanceTaxpayerSharePrefilled(MonetaryNoDecimalsItemType value) {
        this.ownHouseDebtBankAccountBalanceTaxpayerSharePrefilled = value;
    }

    /**
     * Gets the value of the ownHouseDebtBankAccountNumberPrefilled property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring34VItemType }
     *     
     */
    public Anstring34VItemType getOwnHouseDebtBankAccountNumberPrefilled() {
        return ownHouseDebtBankAccountNumberPrefilled;
    }

    /**
     * Sets the value of the ownHouseDebtBankAccountNumberPrefilled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring34VItemType }
     *     
     */
    public void setOwnHouseDebtBankAccountNumberPrefilled(Anstring34VItemType value) {
        this.ownHouseDebtBankAccountNumberPrefilled = value;
    }

    /**
     * Gets the value of the ownHouseDebtBankProductDescriptionPrefilled property.
     * 
     * @return
     *     possible object is
     *     {@link Anstring45VItemType }
     *     
     */
    public Anstring45VItemType getOwnHouseDebtBankProductDescriptionPrefilled() {
        return ownHouseDebtBankProductDescriptionPrefilled;
    }

    /**
     * Sets the value of the ownHouseDebtBankProductDescriptionPrefilled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anstring45VItemType }
     *     
     */
    public void setOwnHouseDebtBankProductDescriptionPrefilled(Anstring45VItemType value) {
        this.ownHouseDebtBankProductDescriptionPrefilled = value;
    }

}
