//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.17 at 01:15:21 PM CEST 
//


package nl.nltaxonomie._8_0_a_2.domein.bd.tuples.bd_burg_tuples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import nl.nltaxonomie._2011.xbrl.xbrl_syntax_extension.Placeholder;
import nl.nltaxonomie._8_0.basis.sbr.types.nl_types.NonNegativeMonetaryNoDecimalsItemType;
import nl.nltaxonomie._8_0_a_2.basis.bd.types.bd_codes.TrainingItemType;
import org.xbrl._2003.instance.DateItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nltaxonomie.nl/2011/xbrl/xbrl-syntax-extension}placeholder">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers}TrainingExpensesStudyFundingYearOfExpenditurePartnerEndDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers}TrainingExpensesStudyFundingYearOfExpenditurePartnerStandardAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers}TrainingExpensesStudyFundingYearOfExpenditurePartnerStartDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers}TrainingExpensesStudyFundingYearOfExpenditurePartnerTrainingType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trainingExpensesStudyFundingYearOfExpenditurePartnerEndDate",
    "trainingExpensesStudyFundingYearOfExpenditurePartnerStandardAmount",
    "trainingExpensesStudyFundingYearOfExpenditurePartnerStartDate",
    "trainingExpensesStudyFundingYearOfExpenditurePartnerTrainingType"
})
public class TrainingExpensesStudyFundingYearOfExpenditurePartnerSpecification
    extends Placeholder
{

    @XmlElement(name = "TrainingExpensesStudyFundingYearOfExpenditurePartnerEndDate", namespace = "http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers")
    protected DateItemType trainingExpensesStudyFundingYearOfExpenditurePartnerEndDate;
    @XmlElement(name = "TrainingExpensesStudyFundingYearOfExpenditurePartnerStandardAmount", namespace = "http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers")
    protected NonNegativeMonetaryNoDecimalsItemType trainingExpensesStudyFundingYearOfExpenditurePartnerStandardAmount;
    @XmlElement(name = "TrainingExpensesStudyFundingYearOfExpenditurePartnerStartDate", namespace = "http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers")
    protected DateItemType trainingExpensesStudyFundingYearOfExpenditurePartnerStartDate;
    @XmlElement(name = "TrainingExpensesStudyFundingYearOfExpenditurePartnerTrainingType", namespace = "http://www.nltaxonomie.nl/8.0.a.2/basis/bd/items/bd-burgers")
    protected TrainingItemType trainingExpensesStudyFundingYearOfExpenditurePartnerTrainingType;

    /**
     * Gets the value of the trainingExpensesStudyFundingYearOfExpenditurePartnerEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateItemType }
     *     
     */
    public DateItemType getTrainingExpensesStudyFundingYearOfExpenditurePartnerEndDate() {
        return trainingExpensesStudyFundingYearOfExpenditurePartnerEndDate;
    }

    /**
     * Sets the value of the trainingExpensesStudyFundingYearOfExpenditurePartnerEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateItemType }
     *     
     */
    public void setTrainingExpensesStudyFundingYearOfExpenditurePartnerEndDate(DateItemType value) {
        this.trainingExpensesStudyFundingYearOfExpenditurePartnerEndDate = value;
    }

    /**
     * Gets the value of the trainingExpensesStudyFundingYearOfExpenditurePartnerStandardAmount property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public NonNegativeMonetaryNoDecimalsItemType getTrainingExpensesStudyFundingYearOfExpenditurePartnerStandardAmount() {
        return trainingExpensesStudyFundingYearOfExpenditurePartnerStandardAmount;
    }

    /**
     * Sets the value of the trainingExpensesStudyFundingYearOfExpenditurePartnerStandardAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeMonetaryNoDecimalsItemType }
     *     
     */
    public void setTrainingExpensesStudyFundingYearOfExpenditurePartnerStandardAmount(NonNegativeMonetaryNoDecimalsItemType value) {
        this.trainingExpensesStudyFundingYearOfExpenditurePartnerStandardAmount = value;
    }

    /**
     * Gets the value of the trainingExpensesStudyFundingYearOfExpenditurePartnerStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateItemType }
     *     
     */
    public DateItemType getTrainingExpensesStudyFundingYearOfExpenditurePartnerStartDate() {
        return trainingExpensesStudyFundingYearOfExpenditurePartnerStartDate;
    }

    /**
     * Sets the value of the trainingExpensesStudyFundingYearOfExpenditurePartnerStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateItemType }
     *     
     */
    public void setTrainingExpensesStudyFundingYearOfExpenditurePartnerStartDate(DateItemType value) {
        this.trainingExpensesStudyFundingYearOfExpenditurePartnerStartDate = value;
    }

    /**
     * Gets the value of the trainingExpensesStudyFundingYearOfExpenditurePartnerTrainingType property.
     * 
     * @return
     *     possible object is
     *     {@link TrainingItemType }
     *     
     */
    public TrainingItemType getTrainingExpensesStudyFundingYearOfExpenditurePartnerTrainingType() {
        return trainingExpensesStudyFundingYearOfExpenditurePartnerTrainingType;
    }

    /**
     * Sets the value of the trainingExpensesStudyFundingYearOfExpenditurePartnerTrainingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainingItemType }
     *     
     */
    public void setTrainingExpensesStudyFundingYearOfExpenditurePartnerTrainingType(TrainingItemType value) {
        this.trainingExpensesStudyFundingYearOfExpenditurePartnerTrainingType = value;
    }

}
